# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ab_ellipse_tester_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1534, 1007)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.k3_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k3_max_spinbox.setMinimum(-10.0)
        self.k3_max_spinbox.setMaximum(10.0)
        self.k3_max_spinbox.setProperty("value", 8.0)
        self.k3_max_spinbox.setObjectName("k3_max_spinbox")
        self.gridLayout.addWidget(self.k3_max_spinbox, 15, 4, 1, 1)
        self.alpha_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_max_spinbox.setMinimum(-10000.0)
        self.alpha_max_spinbox.setMaximum(10000.0)
        self.alpha_max_spinbox.setProperty("value", 50.0)
        self.alpha_max_spinbox.setObjectName("alpha_max_spinbox")
        self.gridLayout.addWidget(self.alpha_max_spinbox, 1, 4, 1, 1)
        self.k4_slider = QtWidgets.QSlider(Dialog)
        self.k4_slider.setProperty("value", 50)
        self.k4_slider.setOrientation(QtCore.Qt.Horizontal)
        self.k4_slider.setObjectName("k4_slider")
        self.gridLayout.addWidget(self.k4_slider, 16, 3, 1, 1)
        self.alpha_slider = QtWidgets.QSlider(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alpha_slider.sizePolicy().hasHeightForWidth())
        self.alpha_slider.setSizePolicy(sizePolicy)
        self.alpha_slider.setMinimumSize(QtCore.QSize(200, 0))
        self.alpha_slider.setMinimum(0)
        self.alpha_slider.setMaximum(99)
        self.alpha_slider.setProperty("value", 50)
        self.alpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_slider.setObjectName("alpha_slider")
        self.gridLayout.addWidget(self.alpha_slider, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 11, 0, 1, 1)
        self.sigma_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_max_spinbox.setDecimals(2)
        self.sigma_max_spinbox.setProperty("value", 1.0)
        self.sigma_max_spinbox.setObjectName("sigma_max_spinbox")
        self.gridLayout.addWidget(self.sigma_max_spinbox, 4, 4, 1, 1)
        self.beta_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_min_spinbox.setMaximum(10000.0)
        self.beta_min_spinbox.setObjectName("beta_min_spinbox")
        self.gridLayout.addWidget(self.beta_min_spinbox, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.k2_slider = QtWidgets.QSlider(Dialog)
        self.k2_slider.setProperty("value", 50)
        self.k2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.k2_slider.setObjectName("k2_slider")
        self.gridLayout.addWidget(self.k2_slider, 14, 3, 1, 1)
        self.alpha_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_spinbox.setMinimumSize(QtCore.QSize(70, 0))
        self.alpha_spinbox.setMinimum(-10000.0)
        self.alpha_spinbox.setMaximum(10000.0)
        self.alpha_spinbox.setObjectName("alpha_spinbox")
        self.gridLayout.addWidget(self.alpha_spinbox, 1, 1, 1, 1)
        self.k1_slider = QtWidgets.QSlider(Dialog)
        self.k1_slider.setProperty("value", 50)
        self.k1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.k1_slider.setObjectName("k1_slider")
        self.gridLayout.addWidget(self.k1_slider, 13, 3, 1, 1)
        self.k1_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k1_max_spinbox.setMinimum(-10.0)
        self.k1_max_spinbox.setMaximum(10.0)
        self.k1_max_spinbox.setProperty("value", 8.0)
        self.k1_max_spinbox.setObjectName("k1_max_spinbox")
        self.gridLayout.addWidget(self.k1_max_spinbox, 13, 4, 1, 1)
        self.k4_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k4_max_spinbox.setMinimum(-10.0)
        self.k4_max_spinbox.setMaximum(10.0)
        self.k4_max_spinbox.setProperty("value", 8.0)
        self.k4_max_spinbox.setObjectName("k4_max_spinbox")
        self.gridLayout.addWidget(self.k4_max_spinbox, 16, 4, 1, 1)
        self.k2_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k2_max_spinbox.setMinimum(-10.0)
        self.k2_max_spinbox.setMaximum(10.0)
        self.k2_max_spinbox.setProperty("value", 8.0)
        self.k2_max_spinbox.setObjectName("k2_max_spinbox")
        self.gridLayout.addWidget(self.k2_max_spinbox, 14, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 19, 0, 1, 1)
        self.alpha_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_min_spinbox.setMinimum(-10000.0)
        self.alpha_min_spinbox.setMaximum(10000.0)
        self.alpha_min_spinbox.setProperty("value", -50.0)
        self.alpha_min_spinbox.setObjectName("alpha_min_spinbox")
        self.gridLayout.addWidget(self.alpha_min_spinbox, 1, 2, 1, 1)
        self.screen_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.screen_max_spinbox.setProperty("value", 2.0)
        self.screen_max_spinbox.setObjectName("screen_max_spinbox")
        self.gridLayout.addWidget(self.screen_max_spinbox, 19, 4, 1, 1)
        self.eps_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_max_spinbox.setProperty("value", 10.0)
        self.eps_max_spinbox.setObjectName("eps_max_spinbox")
        self.gridLayout.addWidget(self.eps_max_spinbox, 3, 4, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.eps_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_spinbox.setMaximum(100.0)
        self.eps_spinbox.setObjectName("eps_spinbox")
        self.gridLayout.addWidget(self.eps_spinbox, 3, 1, 1, 1)
        self.eps_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_min_spinbox.setMinimum(0.1)
        self.eps_min_spinbox.setObjectName("eps_min_spinbox")
        self.gridLayout.addWidget(self.eps_min_spinbox, 3, 2, 1, 1)
        self.k3_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k3_min_spinbox.setMinimum(-10.0)
        self.k3_min_spinbox.setMaximum(10.0)
        self.k3_min_spinbox.setProperty("value", -8.0)
        self.k3_min_spinbox.setObjectName("k3_min_spinbox")
        self.gridLayout.addWidget(self.k3_min_spinbox, 15, 2, 1, 1)
        self.screen_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.screen_spinbox.setProperty("value", 0.0)
        self.screen_spinbox.setObjectName("screen_spinbox")
        self.gridLayout.addWidget(self.screen_spinbox, 19, 1, 1, 1)
        self.energy_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.energy_max_spinbox.setMaximum(3100.0)
        self.energy_max_spinbox.setProperty("value", 1000.0)
        self.energy_max_spinbox.setObjectName("energy_max_spinbox")
        self.gridLayout.addWidget(self.energy_max_spinbox, 11, 4, 1, 1)
        self.energy_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.energy_spinbox.setMaximum(10000.0)
        self.energy_spinbox.setObjectName("energy_spinbox")
        self.gridLayout.addWidget(self.energy_spinbox, 11, 1, 1, 1)
        self.k4_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k4_min_spinbox.setMinimum(-10.0)
        self.k4_min_spinbox.setMaximum(10.0)
        self.k4_min_spinbox.setProperty("value", -8.0)
        self.k4_min_spinbox.setObjectName("k4_min_spinbox")
        self.gridLayout.addWidget(self.k4_min_spinbox, 16, 2, 1, 1)
        self.screen_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.screen_min_spinbox.setObjectName("screen_min_spinbox")
        self.gridLayout.addWidget(self.screen_min_spinbox, 19, 2, 1, 1)
        self.k3_slider = QtWidgets.QSlider(Dialog)
        self.k3_slider.setProperty("value", 50)
        self.k3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.k3_slider.setObjectName("k3_slider")
        self.gridLayout.addWidget(self.k3_slider, 15, 3, 1, 1)
        self.energy_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.energy_min_spinbox.setMinimum(1.0)
        self.energy_min_spinbox.setObjectName("energy_min_spinbox")
        self.gridLayout.addWidget(self.energy_min_spinbox, 11, 2, 1, 1)
        self.k1_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k1_min_spinbox.setMinimum(-10.0)
        self.k1_min_spinbox.setMaximum(10.0)
        self.k1_min_spinbox.setProperty("value", -8.0)
        self.k1_min_spinbox.setObjectName("k1_min_spinbox")
        self.gridLayout.addWidget(self.k1_min_spinbox, 13, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 20, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 14, 0, 1, 1)
        self.eps_slider = QtWidgets.QSlider(Dialog)
        self.eps_slider.setMaximum(99)
        self.eps_slider.setProperty("value", 30)
        self.eps_slider.setOrientation(QtCore.Qt.Horizontal)
        self.eps_slider.setObjectName("eps_slider")
        self.gridLayout.addWidget(self.eps_slider, 3, 3, 1, 1)
        self.energy_slider = QtWidgets.QSlider(Dialog)
        self.energy_slider.setProperty("value", 25)
        self.energy_slider.setOrientation(QtCore.Qt.Horizontal)
        self.energy_slider.setObjectName("energy_slider")
        self.gridLayout.addWidget(self.energy_slider, 11, 3, 1, 1)
        self.screen_slider = QtWidgets.QSlider(Dialog)
        self.screen_slider.setProperty("value", 19)
        self.screen_slider.setOrientation(QtCore.Qt.Horizontal)
        self.screen_slider.setObjectName("screen_slider")
        self.gridLayout.addWidget(self.screen_slider, 19, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 21, 0, 1, 1)
        self.beta_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_max_spinbox.setMaximum(10000.0)
        self.beta_max_spinbox.setProperty("value", 100.0)
        self.beta_max_spinbox.setObjectName("beta_max_spinbox")
        self.gridLayout.addWidget(self.beta_max_spinbox, 2, 4, 1, 1)
        self.k1_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k1_spinbox.setMinimum(-10.0)
        self.k1_spinbox.setMaximum(10.0)
        self.k1_spinbox.setObjectName("k1_spinbox")
        self.gridLayout.addWidget(self.k1_spinbox, 13, 1, 1, 1)
        self.sigma_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_min_spinbox.setObjectName("sigma_min_spinbox")
        self.gridLayout.addWidget(self.sigma_min_spinbox, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 16, 0, 1, 1)
        self.k4_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k4_spinbox.setMinimum(-10.0)
        self.k4_spinbox.setMaximum(10.0)
        self.k4_spinbox.setObjectName("k4_spinbox")
        self.gridLayout.addWidget(self.k4_spinbox, 16, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 12, 0, 1, 1)
        self.sigma_slider = QtWidgets.QSlider(Dialog)
        self.sigma_slider.setProperty("value", 30)
        self.sigma_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sigma_slider.setObjectName("sigma_slider")
        self.gridLayout.addWidget(self.sigma_slider, 4, 3, 1, 1)
        self.k2_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k2_min_spinbox.setMinimum(-10.0)
        self.k2_min_spinbox.setMaximum(10.0)
        self.k2_min_spinbox.setProperty("value", -8.0)
        self.k2_min_spinbox.setObjectName("k2_min_spinbox")
        self.gridLayout.addWidget(self.k2_min_spinbox, 14, 2, 1, 1)
        self.beta_slider = QtWidgets.QSlider(Dialog)
        self.beta_slider.setMaximum(99)
        self.beta_slider.setProperty("value", 50)
        self.beta_slider.setOrientation(QtCore.Qt.Horizontal)
        self.beta_slider.setObjectName("beta_slider")
        self.gridLayout.addWidget(self.beta_slider, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 13, 0, 1, 1)
        self.k3_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k3_spinbox.setMinimum(-10.0)
        self.k3_spinbox.setMaximum(10.0)
        self.k3_spinbox.setObjectName("k3_spinbox")
        self.gridLayout.addWidget(self.k3_spinbox, 15, 1, 1, 1)
        self.sigma_x_label = QtWidgets.QLabel(Dialog)
        self.sigma_x_label.setObjectName("sigma_x_label")
        self.gridLayout.addWidget(self.sigma_x_label, 21, 1, 1, 1)
        self.beta_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_spinbox.setMaximum(10000.0)
        self.beta_spinbox.setObjectName("beta_spinbox")
        self.gridLayout.addWidget(self.beta_spinbox, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 15, 0, 1, 1)
        self.k2_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k2_spinbox.setMinimum(-10.0)
        self.k2_spinbox.setMaximum(10.0)
        self.k2_spinbox.setObjectName("k2_spinbox")
        self.gridLayout.addWidget(self.k2_spinbox, 14, 1, 1, 1)
        self.sigma_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_spinbox.setObjectName("sigma_spinbox")
        self.gridLayout.addWidget(self.sigma_spinbox, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 22, 0, 1, 1)
        self.sigma_y_label = QtWidgets.QLabel(Dialog)
        self.sigma_y_label.setObjectName("sigma_y_label")
        self.gridLayout.addWidget(self.sigma_y_label, 22, 1, 1, 1)
        self.section_combobox = QtWidgets.QComboBox(Dialog)
        self.section_combobox.setCurrentText("")
        self.section_combobox.setObjectName("section_combobox")
        self.gridLayout.addWidget(self.section_combobox, 0, 1, 1, 2)
        self.k5_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k5_max_spinbox.setMinimum(-10.0)
        self.k5_max_spinbox.setMaximum(10.0)
        self.k5_max_spinbox.setProperty("value", 8.0)
        self.k5_max_spinbox.setObjectName("k5_max_spinbox")
        self.gridLayout.addWidget(self.k5_max_spinbox, 17, 4, 1, 1)
        self.k6_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k6_max_spinbox.setMinimum(-10.0)
        self.k6_max_spinbox.setMaximum(10.0)
        self.k6_max_spinbox.setProperty("value", 8.0)
        self.k6_max_spinbox.setObjectName("k6_max_spinbox")
        self.gridLayout.addWidget(self.k6_max_spinbox, 18, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.eps_y_slider = QtWidgets.QSlider(Dialog)
        self.eps_y_slider.setSliderPosition(30)
        self.eps_y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.eps_y_slider.setObjectName("eps_y_slider")
        self.gridLayout.addWidget(self.eps_y_slider, 8, 3, 1, 1)
        self.k5_slider = QtWidgets.QSlider(Dialog)
        self.k5_slider.setProperty("value", 50)
        self.k5_slider.setOrientation(QtCore.Qt.Horizontal)
        self.k5_slider.setObjectName("k5_slider")
        self.gridLayout.addWidget(self.k5_slider, 17, 3, 1, 1)
        self.sigma_y_slider = QtWidgets.QSlider(Dialog)
        self.sigma_y_slider.setProperty("value", 30)
        self.sigma_y_slider.setSliderPosition(30)
        self.sigma_y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sigma_y_slider.setObjectName("sigma_y_slider")
        self.gridLayout.addWidget(self.sigma_y_slider, 9, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 8, 0, 1, 1)
        self.k6_slider = QtWidgets.QSlider(Dialog)
        self.k6_slider.setProperty("value", 50)
        self.k6_slider.setOrientation(QtCore.Qt.Horizontal)
        self.k6_slider.setObjectName("k6_slider")
        self.gridLayout.addWidget(self.k6_slider, 18, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 17, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 9, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 18, 0, 1, 1)
        self.alpha_y_slider = QtWidgets.QSlider(Dialog)
        self.alpha_y_slider.setProperty("value", 50)
        self.alpha_y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_y_slider.setObjectName("alpha_y_slider")
        self.gridLayout.addWidget(self.alpha_y_slider, 6, 3, 1, 1)
        self.alpha_y_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_y_spinbox.setMinimum(-1000.0)
        self.alpha_y_spinbox.setMaximum(1000.0)
        self.alpha_y_spinbox.setObjectName("alpha_y_spinbox")
        self.gridLayout.addWidget(self.alpha_y_spinbox, 6, 1, 1, 1)
        self.beta_y_slider = QtWidgets.QSlider(Dialog)
        self.beta_y_slider.setProperty("value", 50)
        self.beta_y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.beta_y_slider.setObjectName("beta_y_slider")
        self.gridLayout.addWidget(self.beta_y_slider, 7, 3, 1, 1)
        self.alpha_y_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_y_min_spinbox.setMinimum(-10000.0)
        self.alpha_y_min_spinbox.setMaximum(10000.0)
        self.alpha_y_min_spinbox.setProperty("value", -50.0)
        self.alpha_y_min_spinbox.setObjectName("alpha_y_min_spinbox")
        self.gridLayout.addWidget(self.alpha_y_min_spinbox, 6, 2, 1, 1)
        self.alpha_y_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_y_max_spinbox.setMinimum(-10000.0)
        self.alpha_y_max_spinbox.setMaximum(10000.0)
        self.alpha_y_max_spinbox.setProperty("value", 50.0)
        self.alpha_y_max_spinbox.setObjectName("alpha_y_max_spinbox")
        self.gridLayout.addWidget(self.alpha_y_max_spinbox, 6, 4, 1, 1)
        self.beta_y_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_y_spinbox.setMaximum(10000.0)
        self.beta_y_spinbox.setObjectName("beta_y_spinbox")
        self.gridLayout.addWidget(self.beta_y_spinbox, 7, 1, 1, 1)
        self.beta_y_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_y_min_spinbox.setMaximum(10000.0)
        self.beta_y_min_spinbox.setObjectName("beta_y_min_spinbox")
        self.gridLayout.addWidget(self.beta_y_min_spinbox, 7, 2, 1, 1)
        self.beta_y_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_y_max_spinbox.setMaximum(10000.0)
        self.beta_y_max_spinbox.setProperty("value", 100.0)
        self.beta_y_max_spinbox.setObjectName("beta_y_max_spinbox")
        self.gridLayout.addWidget(self.beta_y_max_spinbox, 7, 4, 1, 1)
        self.eps_y_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_y_spinbox.setObjectName("eps_y_spinbox")
        self.gridLayout.addWidget(self.eps_y_spinbox, 8, 1, 1, 1)
        self.sigma_y_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_y_spinbox.setObjectName("sigma_y_spinbox")
        self.gridLayout.addWidget(self.sigma_y_spinbox, 9, 1, 1, 1)
        self.eps_y_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_y_max_spinbox.setMinimum(0.1)
        self.eps_y_max_spinbox.setProperty("value", 10.0)
        self.eps_y_max_spinbox.setObjectName("eps_y_max_spinbox")
        self.gridLayout.addWidget(self.eps_y_max_spinbox, 8, 4, 1, 1)
        self.eps_y_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_y_min_spinbox.setMinimum(0.1)
        self.eps_y_min_spinbox.setObjectName("eps_y_min_spinbox")
        self.gridLayout.addWidget(self.eps_y_min_spinbox, 8, 2, 1, 1)
        self.sigma_y_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_y_max_spinbox.setProperty("value", 1.0)
        self.sigma_y_max_spinbox.setObjectName("sigma_y_max_spinbox")
        self.gridLayout.addWidget(self.sigma_y_max_spinbox, 9, 4, 1, 1)
        self.sigma_y_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_y_min_spinbox.setObjectName("sigma_y_min_spinbox")
        self.gridLayout.addWidget(self.sigma_y_min_spinbox, 9, 2, 1, 1)
        self.k6_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k6_min_spinbox.setMinimum(-10.0)
        self.k6_min_spinbox.setMaximum(10.0)
        self.k6_min_spinbox.setProperty("value", -8.0)
        self.k6_min_spinbox.setObjectName("k6_min_spinbox")
        self.gridLayout.addWidget(self.k6_min_spinbox, 18, 2, 1, 1)
        self.k5_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k5_min_spinbox.setMinimum(-10.0)
        self.k5_min_spinbox.setMaximum(10.0)
        self.k5_min_spinbox.setProperty("value", -8.0)
        self.k5_min_spinbox.setObjectName("k5_min_spinbox")
        self.gridLayout.addWidget(self.k5_min_spinbox, 17, 2, 1, 1)
        self.k6_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k6_spinbox.setMinimum(-10.0)
        self.k6_spinbox.setMaximum(10.0)
        self.k6_spinbox.setObjectName("k6_spinbox")
        self.gridLayout.addWidget(self.k6_spinbox, 18, 1, 1, 1)
        self.k5_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.k5_spinbox.setMinimum(-10.0)
        self.k5_spinbox.setMaximum(10.0)
        self.k5_spinbox.setObjectName("k5_spinbox")
        self.gridLayout.addWidget(self.k5_spinbox, 17, 1, 1, 1)
        self.k_vector_label = QtWidgets.QLabel(Dialog)
        self.k_vector_label.setObjectName("k_vector_label")
        self.gridLayout.addWidget(self.k_vector_label, 23, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widget_2 = ImageView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = PlotWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_3 = PlotWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = PlotWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.alpha_spinbox, self.beta_spinbox)
        Dialog.setTabOrder(self.beta_spinbox, self.eps_spinbox)
        Dialog.setTabOrder(self.eps_spinbox, self.sigma_spinbox)
        Dialog.setTabOrder(self.sigma_spinbox, self.alpha_y_spinbox)
        Dialog.setTabOrder(self.alpha_y_spinbox, self.beta_y_spinbox)
        Dialog.setTabOrder(self.beta_y_spinbox, self.eps_y_spinbox)
        Dialog.setTabOrder(self.eps_y_spinbox, self.sigma_y_spinbox)
        Dialog.setTabOrder(self.sigma_y_spinbox, self.energy_spinbox)
        Dialog.setTabOrder(self.energy_spinbox, self.alpha_min_spinbox)
        Dialog.setTabOrder(self.alpha_min_spinbox, self.beta_min_spinbox)
        Dialog.setTabOrder(self.beta_min_spinbox, self.eps_min_spinbox)
        Dialog.setTabOrder(self.eps_min_spinbox, self.sigma_min_spinbox)
        Dialog.setTabOrder(self.sigma_min_spinbox, self.alpha_y_min_spinbox)
        Dialog.setTabOrder(self.alpha_y_min_spinbox, self.beta_y_min_spinbox)
        Dialog.setTabOrder(self.beta_y_min_spinbox, self.eps_y_min_spinbox)
        Dialog.setTabOrder(self.eps_y_min_spinbox, self.sigma_y_min_spinbox)
        Dialog.setTabOrder(self.sigma_y_min_spinbox, self.energy_min_spinbox)
        Dialog.setTabOrder(self.energy_min_spinbox, self.alpha_max_spinbox)
        Dialog.setTabOrder(self.alpha_max_spinbox, self.beta_max_spinbox)
        Dialog.setTabOrder(self.beta_max_spinbox, self.eps_max_spinbox)
        Dialog.setTabOrder(self.eps_max_spinbox, self.sigma_max_spinbox)
        Dialog.setTabOrder(self.sigma_max_spinbox, self.alpha_y_max_spinbox)
        Dialog.setTabOrder(self.alpha_y_max_spinbox, self.beta_y_max_spinbox)
        Dialog.setTabOrder(self.beta_y_max_spinbox, self.eps_y_max_spinbox)
        Dialog.setTabOrder(self.eps_y_max_spinbox, self.sigma_y_max_spinbox)
        Dialog.setTabOrder(self.sigma_y_max_spinbox, self.energy_max_spinbox)
        Dialog.setTabOrder(self.energy_max_spinbox, self.alpha_slider)
        Dialog.setTabOrder(self.alpha_slider, self.beta_slider)
        Dialog.setTabOrder(self.beta_slider, self.eps_slider)
        Dialog.setTabOrder(self.eps_slider, self.sigma_slider)
        Dialog.setTabOrder(self.sigma_slider, self.alpha_y_slider)
        Dialog.setTabOrder(self.alpha_y_slider, self.beta_y_slider)
        Dialog.setTabOrder(self.beta_y_slider, self.eps_y_slider)
        Dialog.setTabOrder(self.eps_y_slider, self.sigma_y_slider)
        Dialog.setTabOrder(self.sigma_y_slider, self.energy_slider)
        Dialog.setTabOrder(self.energy_slider, self.k1_spinbox)
        Dialog.setTabOrder(self.k1_spinbox, self.k2_spinbox)
        Dialog.setTabOrder(self.k2_spinbox, self.k3_spinbox)
        Dialog.setTabOrder(self.k3_spinbox, self.k4_spinbox)
        Dialog.setTabOrder(self.k4_spinbox, self.k5_spinbox)
        Dialog.setTabOrder(self.k5_spinbox, self.k6_spinbox)
        Dialog.setTabOrder(self.k6_spinbox, self.screen_spinbox)
        Dialog.setTabOrder(self.screen_spinbox, self.k1_min_spinbox)
        Dialog.setTabOrder(self.k1_min_spinbox, self.k2_min_spinbox)
        Dialog.setTabOrder(self.k2_min_spinbox, self.k3_min_spinbox)
        Dialog.setTabOrder(self.k3_min_spinbox, self.k4_min_spinbox)
        Dialog.setTabOrder(self.k4_min_spinbox, self.k5_min_spinbox)
        Dialog.setTabOrder(self.k5_min_spinbox, self.k6_min_spinbox)
        Dialog.setTabOrder(self.k6_min_spinbox, self.screen_min_spinbox)
        Dialog.setTabOrder(self.screen_min_spinbox, self.k1_max_spinbox)
        Dialog.setTabOrder(self.k1_max_spinbox, self.k2_max_spinbox)
        Dialog.setTabOrder(self.k2_max_spinbox, self.k3_max_spinbox)
        Dialog.setTabOrder(self.k3_max_spinbox, self.k4_max_spinbox)
        Dialog.setTabOrder(self.k4_max_spinbox, self.k5_max_spinbox)
        Dialog.setTabOrder(self.k5_max_spinbox, self.k6_max_spinbox)
        Dialog.setTabOrder(self.k6_max_spinbox, self.screen_max_spinbox)
        Dialog.setTabOrder(self.screen_max_spinbox, self.k1_slider)
        Dialog.setTabOrder(self.k1_slider, self.k2_slider)
        Dialog.setTabOrder(self.k2_slider, self.k3_slider)
        Dialog.setTabOrder(self.k3_slider, self.k4_slider)
        Dialog.setTabOrder(self.k4_slider, self.k5_slider)
        Dialog.setTabOrder(self.k5_slider, self.k6_slider)
        Dialog.setTabOrder(self.k6_slider, self.screen_slider)
        Dialog.setTabOrder(self.screen_slider, self.section_combobox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Matching section visualizer"))
        self.label_5.setText(_translate("Dialog", "energy / MeV"))
        self.label_4.setText(_translate("Dialog", "sigma_x / mm"))
        self.label_10.setText(_translate("Dialog", "screen pos"))
        self.label.setText(_translate("Dialog", "alpha_x"))
        self.label_2.setText(_translate("Dialog", "beta_x / m"))
        self.label_3.setText(_translate("Dialog", "eps_n_x / umrad"))
        self.label_9.setText(_translate("Dialog", "k2"))
        self.label_12.setText(_translate("Dialog", "sigma_x"))
        self.label_7.setText(_translate("Dialog", "k4"))
        self.label_6.setText(_translate("Dialog", "k1"))
        self.sigma_x_label.setText(_translate("Dialog", "-.--"))
        self.label_8.setText(_translate("Dialog", "k3"))
        self.label_13.setText(_translate("Dialog", "sigma_y"))
        self.sigma_y_label.setText(_translate("Dialog", "-.--"))
        self.label_14.setText(_translate("Dialog", "Section"))
        self.label_15.setText(_translate("Dialog", "alpha_y"))
        self.label_16.setText(_translate("Dialog", "beta_y / m"))
        self.label_17.setText(_translate("Dialog", "eps_n_y / umrad"))
        self.label_19.setText(_translate("Dialog", "k5"))
        self.label_18.setText(_translate("Dialog", "sigma_y / mm"))
        self.label_20.setText(_translate("Dialog", "k6"))
        self.k_vector_label.setText(_translate("Dialog", "[0.0, 0.0, 0.0, 0.0]"))

from pyqtgraph import ImageView, PlotWidget
