# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ab_ellipse_tester_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1056, 598)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.alpha_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_min_spinbox.setMinimum(-10000.0)
        self.alpha_min_spinbox.setMaximum(10000.0)
        self.alpha_min_spinbox.setProperty("value", -50.0)
        self.alpha_min_spinbox.setObjectName("alpha_min_spinbox")
        self.gridLayout.addWidget(self.alpha_min_spinbox, 0, 1, 1, 1)
        self.beta_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_min_spinbox.setMaximum(10000.0)
        self.beta_min_spinbox.setObjectName("beta_min_spinbox")
        self.gridLayout.addWidget(self.beta_min_spinbox, 1, 1, 1, 1)
        self.alpha_slider = QtWidgets.QSlider(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alpha_slider.sizePolicy().hasHeightForWidth())
        self.alpha_slider.setSizePolicy(sizePolicy)
        self.alpha_slider.setMinimumSize(QtCore.QSize(200, 0))
        self.alpha_slider.setMinimum(0)
        self.alpha_slider.setMaximum(99)
        self.alpha_slider.setProperty("value", 50)
        self.alpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_slider.setObjectName("alpha_slider")
        self.gridLayout.addWidget(self.alpha_slider, 0, 2, 1, 1)
        self.alpha_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_max_spinbox.setMinimum(-10000.0)
        self.alpha_max_spinbox.setMaximum(10000.0)
        self.alpha_max_spinbox.setProperty("value", 50.0)
        self.alpha_max_spinbox.setObjectName("alpha_max_spinbox")
        self.gridLayout.addWidget(self.alpha_max_spinbox, 0, 3, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 7, 1, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 8, 1, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout.addWidget(self.doubleSpinBox_6, 6, 3, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout.addWidget(self.doubleSpinBox_5, 10, 1, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout.addWidget(self.doubleSpinBox_10, 10, 3, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout.addWidget(self.doubleSpinBox_8, 8, 3, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 7, 2, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 6, 2, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout.addWidget(self.doubleSpinBox_4, 9, 1, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout.addWidget(self.doubleSpinBox_9, 9, 3, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout.addWidget(self.doubleSpinBox_7, 7, 3, 1, 1)
        self.horizontalSlider_4 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.gridLayout.addWidget(self.horizontalSlider_4, 9, 2, 1, 1)
        self.horizontalSlider_5 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.gridLayout.addWidget(self.horizontalSlider_5, 10, 2, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout.addWidget(self.horizontalSlider_3, 8, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.eps_slider = QtWidgets.QSlider(Dialog)
        self.eps_slider.setMaximum(99)
        self.eps_slider.setProperty("value", 30)
        self.eps_slider.setOrientation(QtCore.Qt.Horizontal)
        self.eps_slider.setObjectName("eps_slider")
        self.gridLayout.addWidget(self.eps_slider, 2, 2, 1, 1)
        self.eps_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_min_spinbox.setMinimum(0.1)
        self.eps_min_spinbox.setObjectName("eps_min_spinbox")
        self.gridLayout.addWidget(self.eps_min_spinbox, 2, 1, 1, 1)
        self.sigma_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_min_spinbox.setObjectName("sigma_min_spinbox")
        self.gridLayout.addWidget(self.sigma_min_spinbox, 3, 1, 1, 1)
        self.beta_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_max_spinbox.setMaximum(10000.0)
        self.beta_max_spinbox.setProperty("value", 100.0)
        self.beta_max_spinbox.setObjectName("beta_max_spinbox")
        self.gridLayout.addWidget(self.beta_max_spinbox, 1, 3, 1, 1)
        self.energy_min_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.energy_min_spinbox.setMinimum(1.0)
        self.energy_min_spinbox.setObjectName("energy_min_spinbox")
        self.gridLayout.addWidget(self.energy_min_spinbox, 4, 1, 1, 1)
        self.sigma_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_max_spinbox.setProperty("value", 10.0)
        self.sigma_max_spinbox.setObjectName("sigma_max_spinbox")
        self.gridLayout.addWidget(self.sigma_max_spinbox, 3, 3, 1, 1)
        self.eps_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_max_spinbox.setProperty("value", 10.0)
        self.eps_max_spinbox.setObjectName("eps_max_spinbox")
        self.gridLayout.addWidget(self.eps_max_spinbox, 2, 3, 1, 1)
        self.beta_slider = QtWidgets.QSlider(Dialog)
        self.beta_slider.setMaximum(99)
        self.beta_slider.setProperty("value", 50)
        self.beta_slider.setOrientation(QtCore.Qt.Horizontal)
        self.beta_slider.setObjectName("beta_slider")
        self.gridLayout.addWidget(self.beta_slider, 1, 2, 1, 1)
        self.energy_max_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.energy_max_spinbox.setMaximum(1000.0)
        self.energy_max_spinbox.setProperty("value", 1000.0)
        self.energy_max_spinbox.setObjectName("energy_max_spinbox")
        self.gridLayout.addWidget(self.energy_max_spinbox, 4, 3, 1, 1)
        self.energy_slider = QtWidgets.QSlider(Dialog)
        self.energy_slider.setProperty("value", 25)
        self.energy_slider.setOrientation(QtCore.Qt.Horizontal)
        self.energy_slider.setObjectName("energy_slider")
        self.gridLayout.addWidget(self.energy_slider, 4, 2, 1, 1)
        self.sigma_slider = QtWidgets.QSlider(Dialog)
        self.sigma_slider.setProperty("value", 50)
        self.sigma_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sigma_slider.setObjectName("sigma_slider")
        self.gridLayout.addWidget(self.sigma_slider, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.alpha_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.alpha_spinbox.setMinimumSize(QtCore.QSize(70, 0))
        self.alpha_spinbox.setMinimum(-10000.0)
        self.alpha_spinbox.setMaximum(10000.0)
        self.alpha_spinbox.setObjectName("alpha_spinbox")
        self.gridLayout.addWidget(self.alpha_spinbox, 0, 4, 1, 1)
        self.beta_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beta_spinbox.setMaximum(10000.0)
        self.beta_spinbox.setObjectName("beta_spinbox")
        self.gridLayout.addWidget(self.beta_spinbox, 1, 4, 1, 1)
        self.eps_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.eps_spinbox.setMaximum(100.0)
        self.eps_spinbox.setObjectName("eps_spinbox")
        self.gridLayout.addWidget(self.eps_spinbox, 2, 4, 1, 1)
        self.sigma_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.sigma_spinbox.setObjectName("sigma_spinbox")
        self.gridLayout.addWidget(self.sigma_spinbox, 3, 4, 1, 1)
        self.energy_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.energy_spinbox.setMaximum(10000.0)
        self.energy_spinbox.setObjectName("energy_spinbox")
        self.gridLayout.addWidget(self.energy_spinbox, 4, 4, 1, 1)
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.gridLayout.addWidget(self.doubleSpinBox_16, 6, 4, 1, 1)
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.gridLayout.addWidget(self.doubleSpinBox_17, 7, 4, 1, 1)
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.gridLayout.addWidget(self.doubleSpinBox_18, 8, 4, 1, 1)
        self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.gridLayout.addWidget(self.doubleSpinBox_19, 9, 4, 1, 1)
        self.doubleSpinBox_20 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
        self.gridLayout.addWidget(self.doubleSpinBox_20, 10, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.widget = PlotWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "screen pos"))
        self.label_5.setText(_translate("Dialog", "energy / MeV"))
        self.label_4.setText(_translate("Dialog", "sigma / mm"))
        self.label_2.setText(_translate("Dialog", "beta / m"))
        self.label.setText(_translate("Dialog", "alpha"))
        self.label_3.setText(_translate("Dialog", "eps / umrad"))
        self.label_6.setText(_translate("Dialog", "k1"))
        self.label_8.setText(_translate("Dialog", "k3"))
        self.label_7.setText(_translate("Dialog", "k4"))
        self.label_9.setText(_translate("Dialog", "k2"))

from pyqtgraph import PlotWidget
