# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quadscan_gui_notab.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QuadScanDialog(object):
    def setupUi(self, QuadScanDialog):
        QuadScanDialog.setObjectName(_fromUtf8("QuadScanDialog"))
        QuadScanDialog.resize(1265, 881)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QuadScanDialog.sizePolicy().hasHeightForWidth())
        QuadScanDialog.setSizePolicy(sizePolicy)
        QuadScanDialog.setMinimumSize(QtCore.QSize(60, 0))
        QuadScanDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../.designer/backup/eps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QuadScanDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(QuadScanDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_2 = QtGui.QFrame(QuadScanDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.label_8 = QtGui.QLabel(QuadScanDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setContentsMargins(-1, 0, 0, -1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.quad_combobox = QtGui.QComboBox(QuadScanDialog)
        self.quad_combobox.setObjectName(_fromUtf8("quad_combobox"))
        self.gridLayout_8.addWidget(self.quad_combobox, 1, 1, 1, 1)
        self.screen_combobox = QtGui.QComboBox(QuadScanDialog)
        self.screen_combobox.setObjectName(_fromUtf8("screen_combobox"))
        self.gridLayout_8.addWidget(self.screen_combobox, 1, 2, 1, 1)
        self.section_combobox = QtGui.QComboBox(QuadScanDialog)
        self.section_combobox.setObjectName(_fromUtf8("section_combobox"))
        self.gridLayout_8.addWidget(self.section_combobox, 1, 0, 1, 1)
        self.label_25 = QtGui.QLabel(QuadScanDialog)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_8.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_42 = QtGui.QLabel(QuadScanDialog)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_8.addWidget(self.label_42, 0, 1, 1, 1)
        self.label_44 = QtGui.QLabel(QuadScanDialog)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_8.addWidget(self.label_44, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_8, 0, 0, 1, 3)
        self.label_15 = QtGui.QLabel(QuadScanDialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_19 = QtGui.QLabel(QuadScanDialog)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 5, 0, 1, 1)
        self.label_16 = QtGui.QLabel(QuadScanDialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 9, 0, 1, 1)
        self.label_14 = QtGui.QLabel(QuadScanDialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.k_start_spinbox = QtGui.QDoubleSpinBox(QuadScanDialog)
        self.k_start_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.k_start_spinbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.k_start_spinbox.setDecimals(3)
        self.k_start_spinbox.setMinimum(-99.0)
        self.k_start_spinbox.setSingleStep(0.025)
        self.k_start_spinbox.setObjectName(_fromUtf8("k_start_spinbox"))
        self.horizontalLayout_5.addWidget(self.k_start_spinbox)
        self.set_min_button = QtGui.QPushButton(QuadScanDialog)
        self.set_min_button.setMinimumSize(QtCore.QSize(25, 0))
        self.set_min_button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.set_min_button.setObjectName(_fromUtf8("set_min_button"))
        self.horizontalLayout_5.addWidget(self.set_min_button)
        self.label_17 = QtGui.QLabel(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_5.addWidget(self.label_17)
        self.k_end_spinbox = QtGui.QDoubleSpinBox(QuadScanDialog)
        self.k_end_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.k_end_spinbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.k_end_spinbox.setDecimals(3)
        self.k_end_spinbox.setMinimum(-99.0)
        self.k_end_spinbox.setSingleStep(0.025)
        self.k_end_spinbox.setObjectName(_fromUtf8("k_end_spinbox"))
        self.horizontalLayout_5.addWidget(self.k_end_spinbox)
        self.set_max_button = QtGui.QPushButton(QuadScanDialog)
        self.set_max_button.setMinimumSize(QtCore.QSize(25, 0))
        self.set_max_button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.set_max_button.setObjectName(_fromUtf8("set_max_button"))
        self.horizontalLayout_5.addWidget(self.set_max_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 9, 1, 1, 1)
        self.quad_select_edit = QtGui.QLineEdit(QuadScanDialog)
        self.quad_select_edit.setObjectName(_fromUtf8("quad_select_edit"))
        self.gridLayout_3.addWidget(self.quad_select_edit, 2, 1, 1, 1)
        self.screen_select_edit = QtGui.QLineEdit(QuadScanDialog)
        self.screen_select_edit.setObjectName(_fromUtf8("screen_select_edit"))
        self.gridLayout_3.addWidget(self.screen_select_edit, 1, 1, 1, 1)
        self.images_number_spinbox = QtGui.QSpinBox(QuadScanDialog)
        self.images_number_spinbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.images_number_spinbox.setObjectName(_fromUtf8("images_number_spinbox"))
        self.gridLayout_3.addWidget(self.images_number_spinbox, 13, 1, 1, 1)
        self.label_13 = QtGui.QLabel(QuadScanDialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 2, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.k_current_spinbox = QtGui.QDoubleSpinBox(QuadScanDialog)
        self.k_current_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.k_current_spinbox.setDecimals(3)
        self.k_current_spinbox.setMinimum(-99.0)
        self.k_current_spinbox.setSingleStep(0.025)
        self.k_current_spinbox.setObjectName(_fromUtf8("k_current_spinbox"))
        self.horizontalLayout_8.addWidget(self.k_current_spinbox)
        self.k_current_label = QtGui.QLabel(QuadScanDialog)
        self.k_current_label.setMinimumSize(QtCore.QSize(100, 0))
        self.k_current_label.setObjectName(_fromUtf8("k_current_label"))
        self.horizontalLayout_8.addWidget(self.k_current_label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 8, 1, 1, 1)
        self.label_12 = QtGui.QLabel(QuadScanDialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.quad_pos_label = QtGui.QLabel(QuadScanDialog)
        self.quad_pos_label.setObjectName(_fromUtf8("quad_pos_label"))
        self.gridLayout_6.addWidget(self.quad_pos_label, 0, 1, 1, 1)
        self.label_39 = QtGui.QLabel(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 2, 0, 1, 1)
        self.quad_length_label = QtGui.QLabel(QuadScanDialog)
        self.quad_length_label.setObjectName(_fromUtf8("quad_length_label"))
        self.gridLayout_6.addWidget(self.quad_length_label, 1, 1, 1, 1)
        self.label_41 = QtGui.QLabel(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_6.addWidget(self.label_41, 3, 0, 1, 1)
        self.label_27 = QtGui.QLabel(QuadScanDialog)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_6.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_37 = QtGui.QLabel(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_6.addWidget(self.label_37, 0, 0, 1, 1)
        self.quad_state_label = QtGui.QLabel(QuadScanDialog)
        self.quad_state_label.setObjectName(_fromUtf8("quad_state_label"))
        self.gridLayout_6.addWidget(self.quad_state_label, 3, 1, 1, 1)
        self.quad_screen_distance_label = QtGui.QLabel(QuadScanDialog)
        self.quad_screen_distance_label.setObjectName(_fromUtf8("quad_screen_distance_label"))
        self.gridLayout_6.addWidget(self.quad_screen_distance_label, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 5, 1, 1, 1)
        self.label_36 = QtGui.QLabel(QuadScanDialog)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_3.addWidget(self.label_36, 13, 0, 1, 1)
        self.label_43 = QtGui.QLabel(QuadScanDialog)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_3.addWidget(self.label_43, 8, 0, 1, 1)
        self.k_number_values_spinbox = QtGui.QSpinBox(QuadScanDialog)
        self.k_number_values_spinbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.k_number_values_spinbox.setMinimum(1)
        self.k_number_values_spinbox.setMaximum(9999)
        self.k_number_values_spinbox.setProperty("value", 10)
        self.k_number_values_spinbox.setObjectName(_fromUtf8("k_number_values_spinbox"))
        self.gridLayout_3.addWidget(self.k_number_values_spinbox, 12, 1, 1, 1)
        self.label_18 = QtGui.QLabel(QuadScanDialog)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 12, 0, 1, 1)
        self.label_32 = QtGui.QLabel(QuadScanDialog)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 6, 0, 1, 1)
        self.energy_spinbox = QtGui.QDoubleSpinBox(QuadScanDialog)
        self.energy_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.energy_spinbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.energy_spinbox.setDecimals(1)
        self.energy_spinbox.setMaximum(6000.0)
        self.energy_spinbox.setSingleStep(10.0)
        self.energy_spinbox.setProperty("value", 2998.0)
        self.energy_spinbox.setObjectName(_fromUtf8("energy_spinbox"))
        self.gridLayout_3.addWidget(self.energy_spinbox, 6, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.line_8 = QtGui.QFrame(QuadScanDialog)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_3.addWidget(self.line_8)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 6, 6, 6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.camera_start_button = QtGui.QPushButton(QuadScanDialog)
        self.camera_start_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.camera_start_button.setObjectName(_fromUtf8("camera_start_button"))
        self.horizontalLayout_6.addWidget(self.camera_start_button)
        self.camera_stop_button = QtGui.QPushButton(QuadScanDialog)
        self.camera_stop_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.camera_stop_button.setObjectName(_fromUtf8("camera_stop_button"))
        self.horizontalLayout_6.addWidget(self.camera_stop_button)
        self.camera_state_label = QtGui.QLabel(QuadScanDialog)
        self.camera_state_label.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_state_label.setObjectName(_fromUtf8("camera_state_label"))
        self.horizontalLayout_6.addWidget(self.camera_state_label)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 2, 1, 1)
        self.data_base_dir_button = QtGui.QToolButton(QuadScanDialog)
        self.data_base_dir_button.setObjectName(_fromUtf8("data_base_dir_button"))
        self.gridLayout_2.addWidget(self.data_base_dir_button, 4, 3, 1, 1)
        self.label_6 = QtGui.QLabel(QuadScanDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.data_base_dir_edit = QtGui.QLineEdit(QuadScanDialog)
        self.data_base_dir_edit.setObjectName(_fromUtf8("data_base_dir_edit"))
        self.gridLayout_2.addWidget(self.data_base_dir_edit, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(QuadScanDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_22 = QtGui.QLabel(QuadScanDialog)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.scan_start_button = QtGui.QPushButton(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_start_button.sizePolicy().hasHeightForWidth())
        self.scan_start_button.setSizePolicy(sizePolicy)
        self.scan_start_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.scan_start_button.setObjectName(_fromUtf8("scan_start_button"))
        self.horizontalLayout_4.addWidget(self.scan_start_button)
        self.scan_stop_button = QtGui.QPushButton(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_stop_button.sizePolicy().hasHeightForWidth())
        self.scan_stop_button.setSizePolicy(sizePolicy)
        self.scan_stop_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.scan_stop_button.setObjectName(_fromUtf8("scan_stop_button"))
        self.horizontalLayout_4.addWidget(self.scan_stop_button)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(QuadScanDialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(QuadScanDialog)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.load_data_button = QtGui.QPushButton(QuadScanDialog)
        self.load_data_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_data_button.setObjectName(_fromUtf8("load_data_button"))
        self.horizontalLayout_9.addWidget(self.load_data_button)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 5, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.screen_in_button = QtGui.QPushButton(QuadScanDialog)
        self.screen_in_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.screen_in_button.setObjectName(_fromUtf8("screen_in_button"))
        self.horizontalLayout_7.addWidget(self.screen_in_button)
        self.screen_out_button = QtGui.QPushButton(QuadScanDialog)
        self.screen_out_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.screen_out_button.setObjectName(_fromUtf8("screen_out_button"))
        self.horizontalLayout_7.addWidget(self.screen_out_button)
        self.screen_state_label = QtGui.QLabel(QuadScanDialog)
        self.screen_state_label.setMinimumSize(QtCore.QSize(60, 0))
        self.screen_state_label.setObjectName(_fromUtf8("screen_state_label"))
        self.horizontalLayout_7.addWidget(self.screen_state_label)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 2, 1, 1)
        self.label_45 = QtGui.QLabel(QuadScanDialog)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_2.addWidget(self.label_45, 6, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_47 = QtGui.QLabel(QuadScanDialog)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_12.addWidget(self.label_47)
        self.savename_edit = QtGui.QLineEdit(QuadScanDialog)
        self.savename_edit.setObjectName(_fromUtf8("savename_edit"))
        self.horizontalLayout_12.addWidget(self.savename_edit)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 6, 2, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(6, -1, 6, 6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fit_algo_combobox = QtGui.QComboBox(QuadScanDialog)
        self.fit_algo_combobox.setObjectName(_fromUtf8("fit_algo_combobox"))
        self.gridLayout.addWidget(self.fit_algo_combobox, 4, 2, 1, 1)
        self.label_33 = QtGui.QLabel(QuadScanDialog)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.label_33, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(QuadScanDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 7, 1, 1, 1)
        self.label_21 = QtGui.QLabel(QuadScanDialog)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 2, 1, 1, 1)
        self.operation_progressbar = QtGui.QProgressBar(QuadScanDialog)
        self.operation_progressbar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.operation_progressbar.setProperty("value", 0)
        self.operation_progressbar.setObjectName(_fromUtf8("operation_progressbar"))
        self.gridLayout.addWidget(self.operation_progressbar, 8, 1, 1, 2)
        self.state_label = QtGui.QLabel(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state_label.sizePolicy().hasHeightForWidth())
        self.state_label.setSizePolicy(sizePolicy)
        self.state_label.setObjectName(_fromUtf8("state_label"))
        self.gridLayout.addWidget(self.state_label, 6, 2, 1, 1)
        self.label_2 = QtGui.QLabel(QuadScanDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtGui.QLabel(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 6, 1, 1, 1)
        self.threshold_spinbox = QtGui.QDoubleSpinBox(QuadScanDialog)
        self.threshold_spinbox.setDecimals(4)
        self.threshold_spinbox.setMaximum(1.0)
        self.threshold_spinbox.setSingleStep(0.001)
        self.threshold_spinbox.setObjectName(_fromUtf8("threshold_spinbox"))
        self.gridLayout.addWidget(self.threshold_spinbox, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(QuadScanDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 1, 2, 1, 1)
        self.label_34 = QtGui.QLabel(QuadScanDialog)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 3, 1, 1, 1)
        self.median_kernel_spinbox = QtGui.QSpinBox(QuadScanDialog)
        self.median_kernel_spinbox.setMaximum(7)
        self.median_kernel_spinbox.setSingleStep(2)
        self.median_kernel_spinbox.setProperty("value", 3)
        self.median_kernel_spinbox.setObjectName(_fromUtf8("median_kernel_spinbox"))
        self.gridLayout.addWidget(self.median_kernel_spinbox, 3, 2, 1, 1)
        self.process_button = QtGui.QPushButton(QuadScanDialog)
        self.process_button.setMinimumSize(QtCore.QSize(80, 0))
        self.process_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.process_button.setObjectName(_fromUtf8("process_button"))
        self.gridLayout.addWidget(self.process_button, 5, 2, 1, 1)
        self.status_label = QtGui.QTextEdit(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setMinimumSize(QtCore.QSize(0, 80))
        self.status_label.setMaximumSize(QtCore.QSize(16777215, 200))
        self.status_label.setReadOnly(True)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.gridLayout.addWidget(self.status_label, 7, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(QuadScanDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.data_source_label = QtGui.QLabel(QuadScanDialog)
        self.data_source_label.setMinimumSize(QtCore.QSize(10, 0))
        self.data_source_label.setText(_fromUtf8(""))
        self.data_source_label.setObjectName(_fromUtf8("data_source_label"))
        self.horizontalLayout_10.addWidget(self.data_source_label)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, 6, 6, -1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.image_select_label = QtGui.QLabel(QuadScanDialog)
        self.image_select_label.setText(_fromUtf8(""))
        self.image_select_label.setObjectName(_fromUtf8("image_select_label"))
        self.gridLayout_7.addWidget(self.image_select_label, 3, 1, 1, 1)
        self.image_slider = QtGui.QSlider(QuadScanDialog)
        self.image_slider.setMaximum(10)
        self.image_slider.setOrientation(QtCore.Qt.Vertical)
        self.image_slider.setInvertedAppearance(False)
        self.image_slider.setInvertedControls(False)
        self.image_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.image_slider.setTickInterval(1)
        self.image_slider.setObjectName(_fromUtf8("image_slider"))
        self.gridLayout_7.addWidget(self.image_slider, 1, 1, 1, 1)
        self.k_select_label = QtGui.QLabel(QuadScanDialog)
        self.k_select_label.setText(_fromUtf8(""))
        self.k_select_label.setObjectName(_fromUtf8("k_select_label"))
        self.gridLayout_7.addWidget(self.k_select_label, 3, 0, 1, 1)
        self.k_slider = QtGui.QSlider(QuadScanDialog)
        self.k_slider.setMaximum(10)
        self.k_slider.setOrientation(QtCore.Qt.Vertical)
        self.k_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.k_slider.setObjectName(_fromUtf8("k_slider"))
        self.gridLayout_7.addWidget(self.k_slider, 1, 0, 1, 1)
        self.label_38 = QtGui.QLabel(QuadScanDialog)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_7.addWidget(self.label_38, 0, 0, 1, 1)
        self.label_40 = QtGui.QLabel(QuadScanDialog)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_7.addWidget(self.label_40, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_35 = QtGui.QLabel(QuadScanDialog)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_6.addWidget(self.label_35)
        self.image_raw_widget = ImageView(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_raw_widget.sizePolicy().hasHeightForWidth())
        self.image_raw_widget.setSizePolicy(sizePolicy)
        self.image_raw_widget.setObjectName(_fromUtf8("image_raw_widget"))
        self.verticalLayout_6.addWidget(self.image_raw_widget)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.line_6 = QtGui.QFrame(QuadScanDialog)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 6, 6, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_23 = QtGui.QLabel(QuadScanDialog)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_3.addWidget(self.label_23)
        self.image_proc_widget = ImageView(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_proc_widget.sizePolicy().hasHeightForWidth())
        self.image_proc_widget.setSizePolicy(sizePolicy)
        self.image_proc_widget.setObjectName(_fromUtf8("image_proc_widget"))
        self.verticalLayout_3.addWidget(self.image_proc_widget)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 6, 6, -1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_5 = QtGui.QFrame(QuadScanDialog)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout.addWidget(self.line_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_24 = QtGui.QLabel(QuadScanDialog)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_4.addWidget(self.label_24)
        self.lineout_widget = PlotWidget(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineout_widget.sizePolicy().hasHeightForWidth())
        self.lineout_widget.setSizePolicy(sizePolicy)
        self.lineout_widget.setObjectName(_fromUtf8("lineout_widget"))
        self.verticalLayout_4.addWidget(self.lineout_widget)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line_7 = QtGui.QFrame(QuadScanDialog)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_3 = QtGui.QFrame(QuadScanDialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.label_9 = QtGui.QLabel(QuadScanDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 6, 6, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.fit_widget = PlotWidget(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fit_widget.sizePolicy().hasHeightForWidth())
        self.fit_widget.setSizePolicy(sizePolicy)
        self.fit_widget.setObjectName(_fromUtf8("fit_widget"))
        self.horizontalLayout_11.addWidget(self.fit_widget)
        self.charge_widget = PlotWidget(QuadScanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charge_widget.sizePolicy().hasHeightForWidth())
        self.charge_widget.setSizePolicy(sizePolicy)
        self.charge_widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.charge_widget.setObjectName(_fromUtf8("charge_widget"))
        self.horizontalLayout_11.addWidget(self.charge_widget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 6, 6, -1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_29 = QtGui.QLabel(QuadScanDialog)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 3, 0, 1, 1)
        self.eps_label = QtGui.QLabel(QuadScanDialog)
        self.eps_label.setObjectName(_fromUtf8("eps_label"))
        self.gridLayout_5.addWidget(self.eps_label, 2, 1, 1, 1)
        self.label_28 = QtGui.QLabel(QuadScanDialog)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 2, 2, 1, 1)
        self.label_26 = QtGui.QLabel(QuadScanDialog)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_30 = QtGui.QLabel(QuadScanDialog)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(QuadScanDialog)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_31 = QtGui.QLabel(QuadScanDialog)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 4, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 1, 0, 1, 1)
        self.beta_label = QtGui.QLabel(QuadScanDialog)
        self.beta_label.setObjectName(_fromUtf8("beta_label"))
        self.gridLayout_5.addWidget(self.beta_label, 3, 1, 1, 1)
        self.alpha_label = QtGui.QLabel(QuadScanDialog)
        self.alpha_label.setObjectName(_fromUtf8("alpha_label"))
        self.gridLayout_5.addWidget(self.alpha_label, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(QuadScanDialog)
        QtCore.QMetaObject.connectSlotsByName(QuadScanDialog)

    def retranslateUi(self, QuadScanDialog):
        QuadScanDialog.setWindowTitle(_translate("QuadScanDialog", "Quad scan", None))
        self.label_8.setText(_translate("QuadScanDialog", "Scan", None))
        self.label_25.setText(_translate("QuadScanDialog", "Section", None))
        self.label_42.setText(_translate("QuadScanDialog", "Quad", None))
        self.label_44.setText(_translate("QuadScanDialog", "Screen", None))
        self.label_15.setText(_translate("QuadScanDialog", "Valid", None))
        self.label_19.setText(_translate("QuadScanDialog", "Info", None))
        self.label_16.setText(_translate("QuadScanDialog", "K value range", None))
        self.label_14.setText(_translate("QuadScanDialog", "Screen select", None))
        self.set_min_button.setToolTip(_translate("QuadScanDialog", "Set current K-value to min scan range", None))
        self.set_min_button.setText(_translate("QuadScanDialog", "<╝", None))
        self.label_17.setText(_translate("QuadScanDialog", "-", None))
        self.set_max_button.setToolTip(_translate("QuadScanDialog", "Set current K-value to max scan range", None))
        self.set_max_button.setText(_translate("QuadScanDialog", "<╝", None))
        self.label_13.setText(_translate("QuadScanDialog", "Valid", None))
        self.k_current_label.setText(_translate("QuadScanDialog", "--", None))
        self.label_12.setText(_translate("QuadScanDialog", "Quad select", None))
        self.quad_pos_label.setText(_translate("QuadScanDialog", "-- m", None))
        self.label_39.setText(_translate("QuadScanDialog", "Distance quad - screen", None))
        self.quad_length_label.setText(_translate("QuadScanDialog", "-- m", None))
        self.label_41.setText(_translate("QuadScanDialog", "Quad state", None))
        self.label_27.setText(_translate("QuadScanDialog", "Quad length", None))
        self.label_37.setText(_translate("QuadScanDialog", "Quad pos", None))
        self.quad_state_label.setText(_translate("QuadScanDialog", "--", None))
        self.quad_screen_distance_label.setText(_translate("QuadScanDialog", "-- m", None))
        self.label_36.setText(_translate("QuadScanDialog", "Number of images", None))
        self.label_43.setText(_translate("QuadScanDialog", "Current K-value", None))
        self.label_18.setText(_translate("QuadScanDialog", "Number of k-values", None))
        self.label_32.setText(_translate("QuadScanDialog", "Electron energy", None))
        self.energy_spinbox.setSuffix(_translate("QuadScanDialog", " MeV", None))
        self.camera_start_button.setText(_translate("QuadScanDialog", "Start", None))
        self.camera_stop_button.setText(_translate("QuadScanDialog", "Stop", None))
        self.camera_state_label.setText(_translate("QuadScanDialog", "--", None))
        self.data_base_dir_button.setText(_translate("QuadScanDialog", "...", None))
        self.label_6.setText(_translate("QuadScanDialog", "Load data", None))
        self.label_5.setText(_translate("QuadScanDialog", "Data base dir", None))
        self.label_22.setText(_translate("QuadScanDialog", "Camera control", None))
        self.scan_start_button.setText(_translate("QuadScanDialog", "Start", None))
        self.scan_stop_button.setText(_translate("QuadScanDialog", "Stop", None))
        self.label_11.setText(_translate("QuadScanDialog", "Scan", None))
        self.label_20.setText(_translate("QuadScanDialog", "Screen control", None))
        self.load_data_button.setText(_translate("QuadScanDialog", "Load", None))
        self.screen_in_button.setText(_translate("QuadScanDialog", "In", None))
        self.screen_out_button.setText(_translate("QuadScanDialog", "Out", None))
        self.screen_state_label.setText(_translate("QuadScanDialog", "--", None))
        self.label_45.setText(_translate("QuadScanDialog", "Save name", None))
        self.label_47.setToolTip(_translate("QuadScanDialog", "E.g. 2018-04-16_13-40-48_I-MS1-MAG-QB-01_MS1-DIA-SCRN-01", None))
        self.label_47.setText(_translate("QuadScanDialog", "DATE_TIME_QUAD_SCREEN_", None))
        self.savename_edit.setToolTip(_translate("QuadScanDialog", "Extra identifying text in save directory", None))
        self.label_33.setText(_translate("QuadScanDialog", "Fit algo", None))
        self.label_3.setText(_translate("QuadScanDialog", "Status", None))
        self.label_21.setText(_translate("QuadScanDialog", "Threshold", None))
        self.state_label.setText(_translate("QuadScanDialog", "--", None))
        self.label_2.setText(_translate("QuadScanDialog", "--", None))
        self.label.setText(_translate("QuadScanDialog", "State", None))
        self.threshold_spinbox.setToolTip(_translate("QuadScanDialog", "<html><head/><body><p>Threshold intensity for processed image. </p><p>Range 0.0 - 1.0 in absolute units</p></body></html>", None))
        self.label_4.setText(_translate("QuadScanDialog", "ROI", None))
        self.label_34.setText(_translate("QuadScanDialog", "Median kernel size", None))
        self.process_button.setText(_translate("QuadScanDialog", "Process", None))
        self.label_10.setText(_translate("QuadScanDialog", "Data:", None))
        self.data_source_label.setToolTip(_translate("QuadScanDialog", "Name of currently processed dataset", None))
        self.image_select_label.setToolTip(_translate("QuadScanDialog", "Image index for current image", None))
        self.image_slider.setToolTip(_translate("QuadScanDialog", "Image number", None))
        self.k_select_label.setToolTip(_translate("QuadScanDialog", "K value for current image", None))
        self.k_slider.setToolTip(_translate("QuadScanDialog", "Select K number", None))
        self.label_38.setText(_translate("QuadScanDialog", "k", None))
        self.label_40.setText(_translate("QuadScanDialog", "Image", None))
        self.label_35.setText(_translate("QuadScanDialog", "Raw image", None))
        self.image_raw_widget.setToolTip(_translate("QuadScanDialog", "Raw image", None))
        self.label_23.setText(_translate("QuadScanDialog", "Processed image", None))
        self.image_proc_widget.setToolTip(_translate("QuadScanDialog", "Processed image: cropped, thresholded, and filtered", None))
        self.label_24.setText(_translate("QuadScanDialog", "Lineouts", None))
        self.lineout_widget.setToolTip(_translate("QuadScanDialog", "Lineouts of current image", None))
        self.label_9.setText(_translate("QuadScanDialog", "Fit", None))
        self.fit_widget.setToolTip(_translate("QuadScanDialog", "<html><head/><body><p>Fit result. Left click point to enable, right click to disable. </p><p>Click to select point image.</p></body></html>", None))
        self.charge_widget.setToolTip(_translate("QuadScanDialog", "<html><head/><body><p>Integrated charge (from image) in a.u.</p><p>If there is a drop in charge at the limits of the k-values, </p><p>the threshold is probably set too high.</p></body></html>", None))
        self.label_29.setText(_translate("QuadScanDialog", "beta", None))
        self.eps_label.setText(_translate("QuadScanDialog", "--.-", None))
        self.label_28.setText(_translate("QuadScanDialog", "mm x mrad", None))
        self.label_26.setText(_translate("QuadScanDialog", "eps", None))
        self.label_30.setText(_translate("QuadScanDialog", "m", None))
        self.label_7.setText(_translate("QuadScanDialog", "Result", None))
        self.label_31.setText(_translate("QuadScanDialog", "alpha", None))
        self.beta_label.setText(_translate("QuadScanDialog", "--.-", None))
        self.alpha_label.setText(_translate("QuadScanDialog", "--.-", None))

from pyqtgraph import ImageView, PlotWidget
