# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\quadscan_gui_onerow_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QuadScanDialog(object):
    def setupUi(self, QuadScanDialog):
        QuadScanDialog.setObjectName("QuadScanDialog")
        QuadScanDialog.resize(1464, 565)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/eps.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QuadScanDialog.setWindowIcon(icon)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(QuadScanDialog)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tabWidget = QtWidgets.QTabWidget(QuadScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.quad_tab = QtWidgets.QWidget()
        self.quad_tab.setObjectName("quad_tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.quad_tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.quad_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 15, 0, 1, 1)
        self.quad4_label = QtWidgets.QLabel(self.quad_tab)
        self.quad4_label.setObjectName("quad4_label")
        self.gridLayout.addWidget(self.quad4_label, 11, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.quad_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.screen_in_button = QtWidgets.QPushButton(self.quad_tab)
        self.screen_in_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.screen_in_button.setObjectName("screen_in_button")
        self.horizontalLayout_4.addWidget(self.screen_in_button)
        self.screen_out_button = QtWidgets.QPushButton(self.quad_tab)
        self.screen_out_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.screen_out_button.setObjectName("screen_out_button")
        self.horizontalLayout_4.addWidget(self.screen_out_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 16, 1, 1, 1)
        self.electron_energy_spinbox = QtWidgets.QDoubleSpinBox(self.quad_tab)
        self.electron_energy_spinbox.setDecimals(1)
        self.electron_energy_spinbox.setMaximum(5000.0)
        self.electron_energy_spinbox.setObjectName("electron_energy_spinbox")
        self.gridLayout.addWidget(self.electron_energy_spinbox, 6, 1, 1, 1)
        self.quad_combobox = QtWidgets.QComboBox(self.quad_tab)
        self.quad_combobox.setObjectName("quad_combobox")
        self.gridLayout.addWidget(self.quad_combobox, 1, 1, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.quad5_slider = QtWidgets.QSlider(self.quad_tab)
        self.quad5_slider.setEnabled(False)
        self.quad5_slider.setProperty("value", 50)
        self.quad5_slider.setOrientation(QtCore.Qt.Horizontal)
        self.quad5_slider.setObjectName("quad5_slider")
        self.horizontalLayout_23.addWidget(self.quad5_slider)
        self.quad5_spinbox = QtWidgets.QDoubleSpinBox(self.quad_tab)
        self.quad5_spinbox.setEnabled(False)
        self.quad5_spinbox.setMinimum(-99.0)
        self.quad5_spinbox.setSingleStep(0.05)
        self.quad5_spinbox.setObjectName("quad5_spinbox")
        self.horizontalLayout_23.addWidget(self.quad5_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_23, 12, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.quad_tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.quad_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.screen_combobox = QtWidgets.QComboBox(self.quad_tab)
        self.screen_combobox.setObjectName("screen_combobox")
        self.gridLayout.addWidget(self.screen_combobox, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.quad_screen_dist_label = QtWidgets.QLabel(self.quad_tab)
        self.quad_screen_dist_label.setObjectName("quad_screen_dist_label")
        self.gridLayout.addWidget(self.quad_screen_dist_label, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.quad_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.quad3_label = QtWidgets.QLabel(self.quad_tab)
        self.quad3_label.setObjectName("quad3_label")
        self.gridLayout.addWidget(self.quad3_label, 10, 0, 1, 1)
        self.quad5_label = QtWidgets.QLabel(self.quad_tab)
        self.quad5_label.setObjectName("quad5_label")
        self.gridLayout.addWidget(self.quad5_label, 12, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.camera_start_button = QtWidgets.QPushButton(self.quad_tab)
        self.camera_start_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camera_start_button.setObjectName("camera_start_button")
        self.horizontalLayout_3.addWidget(self.camera_start_button)
        self.camera_stop_button = QtWidgets.QPushButton(self.quad_tab)
        self.camera_stop_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camera_stop_button.setObjectName("camera_stop_button")
        self.horizontalLayout_3.addWidget(self.camera_stop_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 15, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.quad_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.quad4_slider = QtWidgets.QSlider(self.quad_tab)
        self.quad4_slider.setEnabled(False)
        self.quad4_slider.setProperty("value", 50)
        self.quad4_slider.setOrientation(QtCore.Qt.Horizontal)
        self.quad4_slider.setObjectName("quad4_slider")
        self.horizontalLayout_22.addWidget(self.quad4_slider)
        self.quad4_spinbox = QtWidgets.QDoubleSpinBox(self.quad_tab)
        self.quad4_spinbox.setEnabled(False)
        self.quad4_spinbox.setMinimum(-99.0)
        self.quad4_spinbox.setSingleStep(0.05)
        self.quad4_spinbox.setObjectName("quad4_spinbox")
        self.horizontalLayout_22.addWidget(self.quad4_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_22, 11, 1, 1, 1)
        self.section_combobox = QtWidgets.QComboBox(self.quad_tab)
        self.section_combobox.setObjectName("section_combobox")
        self.gridLayout.addWidget(self.section_combobox, 0, 1, 1, 1)
        self.quad_length_label = QtWidgets.QLabel(self.quad_tab)
        self.quad_length_label.setObjectName("quad_length_label")
        self.gridLayout.addWidget(self.quad_length_label, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 14, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.quad3_slider = QtWidgets.QSlider(self.quad_tab)
        self.quad3_slider.setEnabled(False)
        self.quad3_slider.setProperty("value", 50)
        self.quad3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.quad3_slider.setObjectName("quad3_slider")
        self.horizontalLayout_21.addWidget(self.quad3_slider)
        self.quad3_spinbox = QtWidgets.QDoubleSpinBox(self.quad_tab)
        self.quad3_spinbox.setEnabled(False)
        self.quad3_spinbox.setMinimum(-99.0)
        self.quad3_spinbox.setSingleStep(0.05)
        self.quad3_spinbox.setObjectName("quad3_spinbox")
        self.horizontalLayout_21.addWidget(self.quad3_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_21, 10, 1, 1, 1)
        self.quad2_label = QtWidgets.QLabel(self.quad_tab)
        self.quad2_label.setObjectName("quad2_label")
        self.gridLayout.addWidget(self.quad2_label, 9, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.quad2_slider = QtWidgets.QSlider(self.quad_tab)
        self.quad2_slider.setEnabled(False)
        self.quad2_slider.setProperty("value", 50)
        self.quad2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.quad2_slider.setObjectName("quad2_slider")
        self.horizontalLayout_20.addWidget(self.quad2_slider)
        self.quad2_spinbox = QtWidgets.QDoubleSpinBox(self.quad_tab)
        self.quad2_spinbox.setEnabled(False)
        self.quad2_spinbox.setMinimum(-99.0)
        self.quad2_spinbox.setSingleStep(0.05)
        self.quad2_spinbox.setObjectName("quad2_spinbox")
        self.horizontalLayout_20.addWidget(self.quad2_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_20, 9, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.quad_tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 16, 0, 1, 1)
        self.quad1_label = QtWidgets.QLabel(self.quad_tab)
        self.quad1_label.setObjectName("quad1_label")
        self.gridLayout.addWidget(self.quad1_label, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.quad_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.quad1_slider = QtWidgets.QSlider(self.quad_tab)
        self.quad1_slider.setEnabled(False)
        self.quad1_slider.setProperty("value", 50)
        self.quad1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.quad1_slider.setObjectName("quad1_slider")
        self.horizontalLayout_19.addWidget(self.quad1_slider)
        self.quad1_spinbox = QtWidgets.QDoubleSpinBox(self.quad_tab)
        self.quad1_spinbox.setEnabled(False)
        self.quad1_spinbox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.quad1_spinbox.setMinimum(-99.0)
        self.quad1_spinbox.setSingleStep(0.05)
        self.quad1_spinbox.setObjectName("quad1_spinbox")
        self.horizontalLayout_19.addWidget(self.quad1_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_19, 8, 1, 1, 1)
        self.quad6_label = QtWidgets.QLabel(self.quad_tab)
        self.quad6_label.setObjectName("quad6_label")
        self.gridLayout.addWidget(self.quad6_label, 13, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.quad6_slider = QtWidgets.QSlider(self.quad_tab)
        self.quad6_slider.setEnabled(False)
        self.quad6_slider.setProperty("value", 50)
        self.quad6_slider.setOrientation(QtCore.Qt.Horizontal)
        self.quad6_slider.setObjectName("quad6_slider")
        self.horizontalLayout_24.addWidget(self.quad6_slider)
        self.quad6_spinbox = QtWidgets.QDoubleSpinBox(self.quad_tab)
        self.quad6_spinbox.setEnabled(False)
        self.quad6_spinbox.setMinimum(-99.0)
        self.quad6_spinbox.setSingleStep(0.05)
        self.quad6_spinbox.setObjectName("quad6_spinbox")
        self.horizontalLayout_24.addWidget(self.quad6_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_24, 13, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.quad_tab, "")
        self.scan_tab = QtWidgets.QWidget()
        self.scan_tab.setObjectName("scan_tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scan_tab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.scan_tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scan_start_button = QtWidgets.QPushButton(self.scan_tab)
        self.scan_start_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.scan_start_button.setObjectName("scan_start_button")
        self.horizontalLayout_9.addWidget(self.scan_start_button)
        self.scan_stop_button = QtWidgets.QPushButton(self.scan_tab)
        self.scan_stop_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.scan_stop_button.setObjectName("scan_stop_button")
        self.horizontalLayout_9.addWidget(self.scan_stop_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 15, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.k_start_spinbox = QtWidgets.QDoubleSpinBox(self.scan_tab)
        self.k_start_spinbox.setDecimals(3)
        self.k_start_spinbox.setMinimum(-1000.0)
        self.k_start_spinbox.setMaximum(1000.0)
        self.k_start_spinbox.setSingleStep(0.1)
        self.k_start_spinbox.setObjectName("k_start_spinbox")
        self.horizontalLayout_8.addWidget(self.k_start_spinbox)
        self.set_start_k_button = QtWidgets.QPushButton(self.scan_tab)
        self.set_start_k_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.set_start_k_button.setObjectName("set_start_k_button")
        self.horizontalLayout_8.addWidget(self.set_start_k_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scan_tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 13, 0, 1, 1)
        self.save_path_linedit = QtWidgets.QLineEdit(self.scan_tab)
        self.save_path_linedit.setObjectName("save_path_linedit")
        self.gridLayout_2.addWidget(self.save_path_linedit, 13, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scan_tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.targetsize_spinbox = QtWidgets.QDoubleSpinBox(self.scan_tab)
        self.targetsize_spinbox.setDecimals(1)
        self.targetsize_spinbox.setMaximum(10000.0)
        self.targetsize_spinbox.setProperty("value", 200.0)
        self.targetsize_spinbox.setObjectName("targetsize_spinbox")
        self.horizontalLayout_25.addWidget(self.targetsize_spinbox)
        self.set_targetsize_button = QtWidgets.QPushButton(self.scan_tab)
        self.set_targetsize_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.set_targetsize_button.setObjectName("set_targetsize_button")
        self.horizontalLayout_25.addWidget(self.set_targetsize_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_25, 6, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scan_tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 10, 0, 1, 1)
        self.update_analysis_radiobutton = QtWidgets.QRadioButton(self.scan_tab)
        self.update_analysis_radiobutton.setChecked(True)
        self.update_analysis_radiobutton.setObjectName("update_analysis_radiobutton")
        self.gridLayout_2.addWidget(self.update_analysis_radiobutton, 16, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scan_tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 1)
        self.k_current_spinbox = QtWidgets.QDoubleSpinBox(self.scan_tab)
        self.k_current_spinbox.setDecimals(3)
        self.k_current_spinbox.setMinimum(-1000.0)
        self.k_current_spinbox.setMaximum(1000.0)
        self.k_current_spinbox.setSingleStep(0.1)
        self.k_current_spinbox.setObjectName("k_current_spinbox")
        self.gridLayout_2.addWidget(self.k_current_spinbox, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.scan_tab)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 6, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.scan_tab)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.save_name_lineedit = QtWidgets.QLineEdit(self.scan_tab)
        self.save_name_lineedit.setObjectName("save_name_lineedit")
        self.horizontalLayout_10.addWidget(self.save_name_lineedit)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 14, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 12, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem7, 7, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scan_tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 8, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.k_end_spinbox = QtWidgets.QDoubleSpinBox(self.scan_tab)
        self.k_end_spinbox.setDecimals(3)
        self.k_end_spinbox.setMinimum(-1000.0)
        self.k_end_spinbox.setMaximum(1000.0)
        self.k_end_spinbox.setSingleStep(0.1)
        self.k_end_spinbox.setObjectName("k_end_spinbox")
        self.horizontalLayout_7.addWidget(self.k_end_spinbox)
        self.set_end_k_button = QtWidgets.QPushButton(self.scan_tab)
        self.set_end_k_button.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.set_end_k_button.setFont(font)
        self.set_end_k_button.setObjectName("set_end_k_button")
        self.horizontalLayout_7.addWidget(self.set_end_k_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 4, 1, 1, 1)
        self.num_k_spinbox = QtWidgets.QSpinBox(self.scan_tab)
        self.num_k_spinbox.setMinimum(1)
        self.num_k_spinbox.setMaximum(1000)
        self.num_k_spinbox.setObjectName("num_k_spinbox")
        self.gridLayout_2.addWidget(self.num_k_spinbox, 8, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scan_tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 9, 0, 1, 1)
        self.reprate_spinbox = QtWidgets.QDoubleSpinBox(self.scan_tab)
        self.reprate_spinbox.setMaximum(200.0)
        self.reprate_spinbox.setObjectName("reprate_spinbox")
        self.gridLayout_2.addWidget(self.reprate_spinbox, 10, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scan_tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 16, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scan_tab)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 15, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scan_tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 14, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.scan_tab)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 0, 0, 1, 1)
        self.num_images_spinbox = QtWidgets.QSpinBox(self.scan_tab)
        self.num_images_spinbox.setMinimum(1)
        self.num_images_spinbox.setMaximum(1000)
        self.num_images_spinbox.setObjectName("num_images_spinbox")
        self.gridLayout_2.addWidget(self.num_images_spinbox, 9, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.scan_tab)
        self.widget.setObjectName("widget")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_26.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.single_quadscan_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.single_quadscan_radiobutton.setChecked(True)
        self.single_quadscan_radiobutton.setObjectName("single_quadscan_radiobutton")
        self.horizontalLayout_26.addWidget(self.single_quadscan_radiobutton)
        self.multi_quadscan_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.multi_quadscan_radiobutton.setObjectName("multi_quadscan_radiobutton")
        self.horizontalLayout_26.addWidget(self.multi_quadscan_radiobutton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem8)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem9, 5, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem10, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.scan_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.p_image_index_slider = QtWidgets.QSlider(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_image_index_slider.sizePolicy().hasHeightForWidth())
        self.p_image_index_slider.setSizePolicy(sizePolicy)
        self.p_image_index_slider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.p_image_index_slider.setMaximum(10)
        self.p_image_index_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_image_index_slider.setInvertedControls(False)
        self.p_image_index_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.p_image_index_slider.setObjectName("p_image_index_slider")
        self.gridLayout_3.addWidget(self.p_image_index_slider, 6, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 14, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 17, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.p_roi_cent_x_spinbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.p_roi_cent_x_spinbox.setMaximum(5000.0)
        self.p_roi_cent_x_spinbox.setObjectName("p_roi_cent_x_spinbox")
        self.horizontalLayout_12.addWidget(self.p_roi_cent_x_spinbox)
        self.p_roi_cent_y_spinbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.p_roi_cent_y_spinbox.setMaximum(5000.0)
        self.p_roi_cent_y_spinbox.setObjectName("p_roi_cent_y_spinbox")
        self.horizontalLayout_12.addWidget(self.p_roi_cent_y_spinbox)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 10, 1, 1, 1)
        self.fit_algo_combobox = QtWidgets.QComboBox(self.tab)
        self.fit_algo_combobox.setObjectName("fit_algo_combobox")
        self.gridLayout_3.addWidget(self.fit_algo_combobox, 17, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 6, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 16, 0, 1, 1)
        self.p_electron_energy_label = QtWidgets.QLabel(self.tab)
        self.p_electron_energy_label.setObjectName("p_electron_energy_label")
        self.gridLayout_3.addWidget(self.p_electron_energy_label, 4, 1, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.p_x_radio = QtWidgets.QRadioButton(self.tab)
        self.p_x_radio.setChecked(True)
        self.p_x_radio.setObjectName("p_x_radio")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(QuadScanDialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.p_x_radio)
        self.horizontalLayout_17.addWidget(self.p_x_radio)
        self.p_y_radio = QtWidgets.QRadioButton(self.tab)
        self.p_y_radio.setObjectName("p_y_radio")
        self.buttonGroup_2.addButton(self.p_y_radio)
        self.horizontalLayout_17.addWidget(self.p_y_radio)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 18, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.p_roi_size_w_spinbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.p_roi_size_w_spinbox.setMaximum(5000.0)
        self.p_roi_size_w_spinbox.setObjectName("p_roi_size_w_spinbox")
        self.horizontalLayout_13.addWidget(self.p_roi_size_w_spinbox)
        self.p_roi_size_h_spinbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.p_roi_size_h_spinbox.setMaximum(5000.0)
        self.p_roi_size_h_spinbox.setObjectName("p_roi_size_h_spinbox")
        self.horizontalLayout_13.addWidget(self.p_roi_size_h_spinbox)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 11, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 11, 0, 1, 1)
        self.p_quad_length_label = QtWidgets.QLabel(self.tab)
        self.p_quad_length_label.setObjectName("p_quad_length_label")
        self.gridLayout_3.addWidget(self.p_quad_length_label, 2, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 18, 0, 1, 1)
        self.process_button = QtWidgets.QPushButton(self.tab)
        self.process_button.setObjectName("process_button")
        self.gridLayout_3.addWidget(self.process_button, 19, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 10, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 8, 0, 1, 1)
        self.p_quad_screen_dist_label = QtWidgets.QLabel(self.tab)
        self.p_quad_screen_dist_label.setObjectName("p_quad_screen_dist_label")
        self.gridLayout_3.addWidget(self.p_quad_screen_dist_label, 3, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 4, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem13, 5, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.p_raw_image_radio = QtWidgets.QRadioButton(self.tab)
        self.p_raw_image_radio.setObjectName("p_raw_image_radio")
        self.buttonGroup = QtWidgets.QButtonGroup(QuadScanDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.p_raw_image_radio)
        self.horizontalLayout_15.addWidget(self.p_raw_image_radio)
        self.p_filtered_image_radio = QtWidgets.QRadioButton(self.tab)
        self.p_filtered_image_radio.setChecked(True)
        self.p_filtered_image_radio.setObjectName("p_filtered_image_radio")
        self.buttonGroup.addButton(self.p_filtered_image_radio)
        self.horizontalLayout_15.addWidget(self.p_filtered_image_radio)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 7, 0, 1, 1)
        self.p_median_kernel_spinbox = QtWidgets.QSpinBox(self.tab)
        self.p_median_kernel_spinbox.setMinimum(1)
        self.p_median_kernel_spinbox.setMaximum(21)
        self.p_median_kernel_spinbox.setSingleStep(2)
        self.p_median_kernel_spinbox.setProperty("value", 3)
        self.p_median_kernel_spinbox.setObjectName("p_median_kernel_spinbox")
        self.gridLayout_3.addWidget(self.p_median_kernel_spinbox, 16, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 15, 0, 1, 1)
        self.p_keep_charge_ratio_spinbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.p_keep_charge_ratio_spinbox.setMaximum(100.0)
        self.p_keep_charge_ratio_spinbox.setProperty("value", 100.0)
        self.p_keep_charge_ratio_spinbox.setObjectName("p_keep_charge_ratio_spinbox")
        self.gridLayout_3.addWidget(self.p_keep_charge_ratio_spinbox, 15, 1, 1, 1)
        self.p_threshold_spinbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.p_threshold_spinbox.setMaximum(66000.0)
        self.p_threshold_spinbox.setObjectName("p_threshold_spinbox")
        self.gridLayout_3.addWidget(self.p_threshold_spinbox, 14, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.load_disk_button = QtWidgets.QPushButton(self.tab)
        self.load_disk_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.load_disk_button.setObjectName("load_disk_button")
        self.horizontalLayout_14.addWidget(self.load_disk_button)
        self.load_scan_button = QtWidgets.QPushButton(self.tab)
        self.load_scan_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.load_scan_button.setObjectName("load_scan_button")
        self.horizontalLayout_14.addWidget(self.load_scan_button)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 0, 1, 1, 1)
        self.data_source_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_source_label.sizePolicy().hasHeightForWidth())
        self.data_source_label.setSizePolicy(sizePolicy)
        self.data_source_label.setObjectName("data_source_label")
        self.gridLayout_3.addWidget(self.data_source_label, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_16.addWidget(self.tabWidget)
        self.widget_9 = QtWidgets.QWidget(QuadScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hor_splitter = QtWidgets.QSplitter(self.widget_9)
        self.hor_splitter.setStyleSheet("QSplitter::handle {\n"
"    image:url(:/icons/hor_split_dots.png);\n"
"    width: 8px;\n"
"    height: 20px;\n"
"}")
        self.hor_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.hor_splitter.setHandleWidth(8)
        self.hor_splitter.setObjectName("hor_splitter")
        self.widget_3 = QtWidgets.QWidget(self.hor_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_splitter = QtWidgets.QSplitter(self.widget_3)
        self.image_splitter.setStyleSheet("QSplitter::handle {\n"
"    image:url(:/icons/vert_split_dots.png);\n"
"    width: 20px;\n"
"    height: 8px;\n"
"}")
        self.image_splitter.setOrientation(QtCore.Qt.Vertical)
        self.image_splitter.setHandleWidth(5)
        self.image_splitter.setObjectName("image_splitter")
        self.layoutWidget = QtWidgets.QWidget(self.image_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.screen_state_label = QtWidgets.QLabel(self.layoutWidget)
        self.screen_state_label.setObjectName("screen_state_label")
        self.horizontalLayout_2.addWidget(self.screen_state_label)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.camera_state_label = QtWidgets.QLabel(self.layoutWidget)
        self.camera_state_label.setObjectName("camera_state_label")
        self.horizontalLayout_2.addWidget(self.camera_state_label)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.reprate_label = QtWidgets.QLabel(self.layoutWidget)
        self.reprate_label.setObjectName("reprate_label")
        self.horizontalLayout_2.addWidget(self.reprate_label)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.scan_status_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.scan_status_label.setFont(font)
        self.scan_status_label.setObjectName("scan_status_label")
        self.horizontalLayout_2.addWidget(self.scan_status_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.camera_widget = ImageView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_widget.sizePolicy().hasHeightForWidth())
        self.camera_widget.setSizePolicy(sizePolicy)
        self.camera_widget.setObjectName("camera_widget")
        self.verticalLayout_3.addWidget(self.camera_widget)
        self.widget_7 = QtWidgets.QWidget(self.image_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setContentsMargins(0, 6, 6, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.line_10 = QtWidgets.QFrame(self.widget_7)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_11.addWidget(self.line_10)
        self.p_k_value_label = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.p_k_value_label.setFont(font)
        self.p_k_value_label.setObjectName("p_k_value_label")
        self.horizontalLayout_11.addWidget(self.p_k_value_label)
        self.line_8 = QtWidgets.QFrame(self.widget_7)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_11.addWidget(self.line_8)
        self.p_k_ind_label = QtWidgets.QLabel(self.widget_7)
        self.p_k_ind_label.setObjectName("p_k_ind_label")
        self.horizontalLayout_11.addWidget(self.p_k_ind_label)
        self.line_9 = QtWidgets.QFrame(self.widget_7)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_11.addWidget(self.line_9)
        self.p_image_label = QtWidgets.QLabel(self.widget_7)
        self.p_image_label.setObjectName("p_image_label")
        self.horizontalLayout_11.addWidget(self.p_image_label)
        self.line_11 = QtWidgets.QFrame(self.widget_7)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_11.addWidget(self.line_11)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.process_image_widget = ImageView(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_image_widget.sizePolicy().hasHeightForWidth())
        self.process_image_widget.setSizePolicy(sizePolicy)
        self.process_image_widget.setObjectName("process_image_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.process_image_widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6.addWidget(self.process_image_widget)
        self.verticalLayout_2.addWidget(self.image_splitter)
        self.widget_6 = QtWidgets.QWidget(self.hor_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.widget_6)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem18)
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setMinimumSize(QtCore.QSize(20, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_27.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.enable_point_radioutton = QtWidgets.QRadioButton(self.widget_2)
        self.enable_point_radioutton.setObjectName("enable_point_radioutton")
        self.horizontalLayout_27.addWidget(self.enable_point_radioutton)
        self.toggle_point_radiobutton = QtWidgets.QRadioButton(self.widget_2)
        self.toggle_point_radiobutton.setChecked(True)
        self.toggle_point_radiobutton.setObjectName("toggle_point_radiobutton")
        self.horizontalLayout_27.addWidget(self.toggle_point_radiobutton)
        self.disable_point_radiobutton = QtWidgets.QRadioButton(self.widget_2)
        self.disable_point_radiobutton.setObjectName("disable_point_radiobutton")
        self.horizontalLayout_27.addWidget(self.disable_point_radiobutton)
        self.horizontalLayout_18.addWidget(self.widget_2)
        self.p_enable_all_button = QtWidgets.QPushButton(self.widget_4)
        self.p_enable_all_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.p_enable_all_button.setFont(font)
        self.p_enable_all_button.setObjectName("p_enable_all_button")
        self.horizontalLayout_18.addWidget(self.p_enable_all_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.analysis_plots_splitter = QtWidgets.QSplitter(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysis_plots_splitter.sizePolicy().hasHeightForWidth())
        self.analysis_plots_splitter.setSizePolicy(sizePolicy)
        self.analysis_plots_splitter.setStyleSheet("QSplitter::handle {\n"
"    image:url(:/icons/vert_split_dots.png);\n"
"    width: 20px;\n"
"    height: 10px;\n"
"}")
        self.analysis_plots_splitter.setOrientation(QtCore.Qt.Vertical)
        self.analysis_plots_splitter.setHandleWidth(5)
        self.analysis_plots_splitter.setObjectName("analysis_plots_splitter")
        self.charge_widget_2 = QtWidgets.QWidget(self.analysis_plots_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charge_widget_2.sizePolicy().hasHeightForWidth())
        self.charge_widget_2.setSizePolicy(sizePolicy)
        self.charge_widget_2.setObjectName("charge_widget_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.charge_widget_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 6)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.fit_widget = QTangoStripTool(self.charge_widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fit_widget.sizePolicy().hasHeightForWidth())
        self.fit_widget.setSizePolicy(sizePolicy)
        self.fit_widget.setObjectName("fit_widget")
        self.verticalLayout_11.addWidget(self.fit_widget)
        self.widget_8 = QtWidgets.QWidget(self.analysis_plots_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_12.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.charge_widget = QTangoStripTool(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charge_widget.sizePolicy().hasHeightForWidth())
        self.charge_widget.setSizePolicy(sizePolicy)
        self.charge_widget.setObjectName("charge_widget")
        self.verticalLayout_12.addWidget(self.charge_widget)
        self.verticalLayout_8.addWidget(self.analysis_plots_splitter)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.hor_splitter)
        self.horizontalLayout_16.addWidget(self.widget_9)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, 6, -1)
        self.gridLayout_4.setHorizontalSpacing(3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_37 = QtWidgets.QLabel(QuadScanDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 4, 0, 1, 1)
        self.beta_label = QtWidgets.QLabel(QuadScanDialog)
        self.beta_label.setMinimumSize(QtCore.QSize(60, 0))
        self.beta_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.beta_label.setFont(font)
        self.beta_label.setObjectName("beta_label")
        self.gridLayout_4.addWidget(self.beta_label, 4, 2, 1, 1)
        self.eps_label = QtWidgets.QLabel(QuadScanDialog)
        self.eps_label.setMinimumSize(QtCore.QSize(60, 0))
        self.eps_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.eps_label.setFont(font)
        self.eps_label.setObjectName("eps_label")
        self.gridLayout_4.addWidget(self.eps_label, 5, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(QuadScanDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 9, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(QuadScanDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 3, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(QuadScanDialog)
        self.label_41.setMinimumSize(QtCore.QSize(60, 0))
        self.label_41.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 1, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(QuadScanDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 5, 0, 1, 1)
        self.result_label = QtWidgets.QLabel(QuadScanDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.gridLayout_4.addWidget(self.result_label, 0, 0, 1, 1)
        self.alpha_y_label = QtWidgets.QLabel(QuadScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alpha_y_label.sizePolicy().hasHeightForWidth())
        self.alpha_y_label.setSizePolicy(sizePolicy)
        self.alpha_y_label.setMinimumSize(QtCore.QSize(60, 0))
        self.alpha_y_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.alpha_y_label.setFont(font)
        self.alpha_y_label.setObjectName("alpha_y_label")
        self.gridLayout_4.addWidget(self.alpha_y_label, 3, 3, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem19, 6, 0, 1, 1)
        self.result_axis_label = QtWidgets.QLabel(QuadScanDialog)
        self.result_axis_label.setMinimumSize(QtCore.QSize(60, 0))
        self.result_axis_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.result_axis_label.setFont(font)
        self.result_axis_label.setObjectName("result_axis_label")
        self.gridLayout_4.addWidget(self.result_axis_label, 1, 2, 1, 1)
        self.alpha_label = QtWidgets.QLabel(QuadScanDialog)
        self.alpha_label.setMinimumSize(QtCore.QSize(60, 0))
        self.alpha_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.alpha_label.setFont(font)
        self.alpha_label.setObjectName("alpha_label")
        self.gridLayout_4.addWidget(self.alpha_label, 3, 2, 1, 1)
        self.beta_y_label = QtWidgets.QLabel(QuadScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beta_y_label.sizePolicy().hasHeightForWidth())
        self.beta_y_label.setSizePolicy(sizePolicy)
        self.beta_y_label.setMinimumSize(QtCore.QSize(60, 0))
        self.beta_y_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.beta_y_label.setFont(font)
        self.beta_y_label.setObjectName("beta_y_label")
        self.gridLayout_4.addWidget(self.beta_y_label, 4, 3, 1, 1)
        self.eps_y_label = QtWidgets.QLabel(QuadScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eps_y_label.sizePolicy().hasHeightForWidth())
        self.eps_y_label.setSizePolicy(sizePolicy)
        self.eps_y_label.setMinimumSize(QtCore.QSize(60, 0))
        self.eps_y_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.eps_y_label.setFont(font)
        self.eps_y_label.setObjectName("eps_y_label")
        self.gridLayout_4.addWidget(self.eps_y_label, 5, 3, 1, 1)
        self.mouse_label = QtWidgets.QLabel(QuadScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouse_label.sizePolicy().hasHeightForWidth())
        self.mouse_label.setSizePolicy(sizePolicy)
        self.mouse_label.setMinimumSize(QtCore.QSize(120, 0))
        self.mouse_label.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.mouse_label.setFont(font)
        self.mouse_label.setObjectName("mouse_label")
        self.gridLayout_4.addWidget(self.mouse_label, 9, 2, 1, 2)
        self.label_40 = QtWidgets.QLabel(QuadScanDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 7, 0, 1, 1)
        self.charge_ratio_label = QtWidgets.QLabel(QuadScanDialog)
        self.charge_ratio_label.setText("")
        self.charge_ratio_label.setObjectName("charge_ratio_label")
        self.gridLayout_4.addWidget(self.charge_ratio_label, 2, 2, 1, 2)
        self.status_textedit = QtWidgets.QTextEdit(QuadScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_textedit.sizePolicy().hasHeightForWidth())
        self.status_textedit.setSizePolicy(sizePolicy)
        self.status_textedit.setMinimumSize(QtCore.QSize(210, 0))
        self.status_textedit.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.status_textedit.setFont(font)
        self.status_textedit.setReadOnly(True)
        self.status_textedit.setObjectName("status_textedit")
        self.gridLayout_4.addWidget(self.status_textedit, 8, 0, 1, 4)
        self.horizontalLayout_16.addLayout(self.gridLayout_4)

        self.retranslateUi(QuadScanDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QuadScanDialog)
        QuadScanDialog.setTabOrder(self.section_combobox, self.quad_combobox)
        QuadScanDialog.setTabOrder(self.quad_combobox, self.screen_combobox)
        QuadScanDialog.setTabOrder(self.screen_combobox, self.electron_energy_spinbox)
        QuadScanDialog.setTabOrder(self.electron_energy_spinbox, self.quad1_slider)
        QuadScanDialog.setTabOrder(self.quad1_slider, self.quad1_spinbox)
        QuadScanDialog.setTabOrder(self.quad1_spinbox, self.quad2_slider)
        QuadScanDialog.setTabOrder(self.quad2_slider, self.quad2_spinbox)
        QuadScanDialog.setTabOrder(self.quad2_spinbox, self.quad3_slider)
        QuadScanDialog.setTabOrder(self.quad3_slider, self.quad3_spinbox)
        QuadScanDialog.setTabOrder(self.quad3_spinbox, self.quad4_slider)
        QuadScanDialog.setTabOrder(self.quad4_slider, self.quad4_spinbox)
        QuadScanDialog.setTabOrder(self.quad4_spinbox, self.quad5_slider)
        QuadScanDialog.setTabOrder(self.quad5_slider, self.quad5_spinbox)
        QuadScanDialog.setTabOrder(self.quad5_spinbox, self.quad6_slider)
        QuadScanDialog.setTabOrder(self.quad6_slider, self.quad6_spinbox)
        QuadScanDialog.setTabOrder(self.quad6_spinbox, self.camera_start_button)
        QuadScanDialog.setTabOrder(self.camera_start_button, self.camera_stop_button)
        QuadScanDialog.setTabOrder(self.camera_stop_button, self.screen_in_button)
        QuadScanDialog.setTabOrder(self.screen_in_button, self.screen_out_button)
        QuadScanDialog.setTabOrder(self.screen_out_button, self.single_quadscan_radiobutton)
        QuadScanDialog.setTabOrder(self.single_quadscan_radiobutton, self.multi_quadscan_radiobutton)
        QuadScanDialog.setTabOrder(self.multi_quadscan_radiobutton, self.k_current_spinbox)
        QuadScanDialog.setTabOrder(self.k_current_spinbox, self.k_start_spinbox)
        QuadScanDialog.setTabOrder(self.k_start_spinbox, self.set_start_k_button)
        QuadScanDialog.setTabOrder(self.set_start_k_button, self.k_end_spinbox)
        QuadScanDialog.setTabOrder(self.k_end_spinbox, self.set_end_k_button)
        QuadScanDialog.setTabOrder(self.set_end_k_button, self.targetsize_spinbox)
        QuadScanDialog.setTabOrder(self.targetsize_spinbox, self.set_targetsize_button)
        QuadScanDialog.setTabOrder(self.set_targetsize_button, self.num_k_spinbox)
        QuadScanDialog.setTabOrder(self.num_k_spinbox, self.num_images_spinbox)
        QuadScanDialog.setTabOrder(self.num_images_spinbox, self.reprate_spinbox)
        QuadScanDialog.setTabOrder(self.reprate_spinbox, self.save_path_linedit)
        QuadScanDialog.setTabOrder(self.save_path_linedit, self.save_name_lineedit)
        QuadScanDialog.setTabOrder(self.save_name_lineedit, self.scan_start_button)
        QuadScanDialog.setTabOrder(self.scan_start_button, self.scan_stop_button)
        QuadScanDialog.setTabOrder(self.scan_stop_button, self.update_analysis_radiobutton)
        QuadScanDialog.setTabOrder(self.update_analysis_radiobutton, self.load_disk_button)
        QuadScanDialog.setTabOrder(self.load_disk_button, self.load_scan_button)
        QuadScanDialog.setTabOrder(self.load_scan_button, self.p_image_index_slider)
        QuadScanDialog.setTabOrder(self.p_image_index_slider, self.p_raw_image_radio)
        QuadScanDialog.setTabOrder(self.p_raw_image_radio, self.p_filtered_image_radio)
        QuadScanDialog.setTabOrder(self.p_filtered_image_radio, self.p_roi_cent_x_spinbox)
        QuadScanDialog.setTabOrder(self.p_roi_cent_x_spinbox, self.p_roi_cent_y_spinbox)
        QuadScanDialog.setTabOrder(self.p_roi_cent_y_spinbox, self.p_roi_size_w_spinbox)
        QuadScanDialog.setTabOrder(self.p_roi_size_w_spinbox, self.p_roi_size_h_spinbox)
        QuadScanDialog.setTabOrder(self.p_roi_size_h_spinbox, self.p_threshold_spinbox)
        QuadScanDialog.setTabOrder(self.p_threshold_spinbox, self.p_keep_charge_ratio_spinbox)
        QuadScanDialog.setTabOrder(self.p_keep_charge_ratio_spinbox, self.p_median_kernel_spinbox)
        QuadScanDialog.setTabOrder(self.p_median_kernel_spinbox, self.fit_algo_combobox)
        QuadScanDialog.setTabOrder(self.fit_algo_combobox, self.p_x_radio)
        QuadScanDialog.setTabOrder(self.p_x_radio, self.p_y_radio)
        QuadScanDialog.setTabOrder(self.p_y_radio, self.process_button)
        QuadScanDialog.setTabOrder(self.process_button, self.enable_point_radioutton)
        QuadScanDialog.setTabOrder(self.enable_point_radioutton, self.toggle_point_radiobutton)
        QuadScanDialog.setTabOrder(self.toggle_point_radiobutton, self.disable_point_radiobutton)
        QuadScanDialog.setTabOrder(self.disable_point_radiobutton, self.p_enable_all_button)

    def retranslateUi(self, QuadScanDialog):
        _translate = QtCore.QCoreApplication.translate
        QuadScanDialog.setWindowTitle(_translate("QuadScanDialog", "Quad scan"))
        self.label_7.setText(_translate("QuadScanDialog", "Camera"))
        self.quad4_label.setText(_translate("QuadScanDialog", "Quad 4"))
        self.label_3.setText(_translate("QuadScanDialog", "Screen"))
        self.screen_in_button.setText(_translate("QuadScanDialog", "In"))
        self.screen_out_button.setText(_translate("QuadScanDialog", "Out"))
        self.electron_energy_spinbox.setSuffix(_translate("QuadScanDialog", " MeV"))
        self.label.setText(_translate("QuadScanDialog", "Section"))
        self.label_5.setText(_translate("QuadScanDialog", "Quad-screen dist"))
        self.quad_screen_dist_label.setText(_translate("QuadScanDialog", "-.--"))
        self.label_2.setText(_translate("QuadScanDialog", "Quad"))
        self.quad3_label.setText(_translate("QuadScanDialog", "Quad 3"))
        self.quad5_label.setText(_translate("QuadScanDialog", "Quad 5"))
        self.camera_start_button.setText(_translate("QuadScanDialog", "Start"))
        self.camera_stop_button.setText(_translate("QuadScanDialog", "Stop"))
        self.label_6.setText(_translate("QuadScanDialog", "Electron energy"))
        self.quad_length_label.setText(_translate("QuadScanDialog", "-.--"))
        self.quad2_label.setText(_translate("QuadScanDialog", "Quad 2"))
        self.label_8.setText(_translate("QuadScanDialog", "Screen"))
        self.quad1_label.setText(_translate("QuadScanDialog", "Quad 1"))
        self.label_4.setText(_translate("QuadScanDialog", "Quad length"))
        self.quad6_label.setText(_translate("QuadScanDialog", "Quad 6"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.quad_tab), _translate("QuadScanDialog", "Magnets"))
        self.label_14.setText(_translate("QuadScanDialog", "k start"))
        self.scan_start_button.setText(_translate("QuadScanDialog", "SCAN"))
        self.scan_stop_button.setText(_translate("QuadScanDialog", "STOP"))
        self.k_start_spinbox.setSuffix(_translate("QuadScanDialog", " 1/m²"))
        self.set_start_k_button.setText(_translate("QuadScanDialog", "<╝"))
        self.label_19.setText(_translate("QuadScanDialog", "Save dir"))
        self.label_13.setText(_translate("QuadScanDialog", "k current"))
        self.targetsize_spinbox.setSuffix(_translate("QuadScanDialog", " µm"))
        self.set_targetsize_button.setText(_translate("QuadScanDialog", "<╝"))
        self.label_18.setText(_translate("QuadScanDialog", "Rep rate"))
        self.update_analysis_radiobutton.setText(_translate("QuadScanDialog", "Update while scan"))
        self.label_15.setText(_translate("QuadScanDialog", "k end"))
        self.k_current_spinbox.setSuffix(_translate("QuadScanDialog", " 1/m²"))
        self.label_34.setText(_translate("QuadScanDialog", "Target size"))
        self.label_22.setText(_translate("QuadScanDialog", "TextLabel"))
        self.label_16.setText(_translate("QuadScanDialog", "Num k"))
        self.k_end_spinbox.setSuffix(_translate("QuadScanDialog", " 1/m²"))
        self.set_end_k_button.setText(_translate("QuadScanDialog", "<╝"))
        self.label_17.setText(_translate("QuadScanDialog", "Num images"))
        self.label_9.setText(_translate("QuadScanDialog", "Analysis"))
        self.label_21.setText(_translate("QuadScanDialog", "Scan"))
        self.label_20.setText(_translate("QuadScanDialog", "Save name"))
        self.label_36.setText(_translate("QuadScanDialog", "Scan type"))
        self.single_quadscan_radiobutton.setText(_translate("QuadScanDialog", "Single"))
        self.multi_quadscan_radiobutton.setText(_translate("QuadScanDialog", "Multi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scan_tab), _translate("QuadScanDialog", "Scan"))
        self.label_28.setText(_translate("QuadScanDialog", "Background level"))
        self.label_30.setText(_translate("QuadScanDialog", "Fit algorithm"))
        self.label_32.setText(_translate("QuadScanDialog", "Select image"))
        self.label_24.setText(_translate("QuadScanDialog", "Quad screen dist"))
        self.label_29.setText(_translate("QuadScanDialog", "Median kernel"))
        self.p_electron_energy_label.setText(_translate("QuadScanDialog", "--- MeV"))
        self.p_x_radio.setText(_translate("QuadScanDialog", "x"))
        self.p_y_radio.setText(_translate("QuadScanDialog", "y"))
        self.label_27.setText(_translate("QuadScanDialog", "ROI size (w / h)"))
        self.p_quad_length_label.setText(_translate("QuadScanDialog", "-.-- m"))
        self.label_33.setText(_translate("QuadScanDialog", "Axis"))
        self.process_button.setText(_translate("QuadScanDialog", "Process"))
        self.label_26.setText(_translate("QuadScanDialog", "ROI cent (x, y)"))
        self.p_quad_screen_dist_label.setText(_translate("QuadScanDialog", "-.-- m"))
        self.label_25.setText(_translate("QuadScanDialog", "Electron energy"))
        self.p_raw_image_radio.setText(_translate("QuadScanDialog", "Raw"))
        self.p_filtered_image_radio.setText(_translate("QuadScanDialog", "Processed"))
        self.label_11.setText(_translate("QuadScanDialog", "Show"))
        self.label_23.setText(_translate("QuadScanDialog", "Quad length"))
        self.label_31.setText(_translate("QuadScanDialog", "Fit using charge"))
        self.p_keep_charge_ratio_spinbox.setSuffix(_translate("QuadScanDialog", " %"))
        self.label_10.setText(_translate("QuadScanDialog", "Load data from"))
        self.load_disk_button.setText(_translate("QuadScanDialog", "DISK"))
        self.load_scan_button.setText(_translate("QuadScanDialog", "Scan"))
        self.data_source_label.setText(_translate("QuadScanDialog", "--- No data loaded ---"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("QuadScanDialog", "Analysis"))
        self.screen_state_label.setText(_translate("QuadScanDialog", "IN"))
        self.camera_state_label.setText(_translate("QuadScanDialog", "RUNNING"))
        self.reprate_label.setText(_translate("QuadScanDialog", "-- Hz"))
        self.scan_status_label.setText(_translate("QuadScanDialog", "PAUSED: k -/- image -/- "))
        self.p_k_value_label.setText(_translate("QuadScanDialog", "k = -.-- 1/m²"))
        self.p_k_ind_label.setText(_translate("QuadScanDialog", "k index 0/0"))
        self.p_image_label.setText(_translate("QuadScanDialog", "image 0/0"))
        self.label_12.setText(_translate("QuadScanDialog", "    Fit"))
        self.enable_point_radioutton.setText(_translate("QuadScanDialog", "Enable"))
        self.toggle_point_radiobutton.setText(_translate("QuadScanDialog", "Toggle"))
        self.disable_point_radiobutton.setText(_translate("QuadScanDialog", "Disable"))
        self.p_enable_all_button.setText(_translate("QuadScanDialog", "Do all"))
        self.label_37.setText(_translate("QuadScanDialog", "β / m"))
        self.beta_label.setText(_translate("QuadScanDialog", "--.-"))
        self.eps_label.setText(_translate("QuadScanDialog", "--.-"))
        self.label_39.setText(_translate("QuadScanDialog", "Mouse"))
        self.label_38.setText(_translate("QuadScanDialog", "α"))
        self.label_41.setText(_translate("QuadScanDialog", "y-axis"))
        self.label_35.setText(_translate("QuadScanDialog", "<html><head/><body><p>ε<span style=\" vertical-align:sub;\">N</span> / µm x rad</p></body></html>"))
        self.result_label.setText(_translate("QuadScanDialog", "Result"))
        self.alpha_y_label.setText(_translate("QuadScanDialog", "--.-"))
        self.result_axis_label.setText(_translate("QuadScanDialog", "x-axis"))
        self.alpha_label.setText(_translate("QuadScanDialog", "--.-"))
        self.beta_y_label.setText(_translate("QuadScanDialog", "--.-"))
        self.eps_y_label.setText(_translate("QuadScanDialog", "--.-"))
        self.mouse_label.setText(_translate("QuadScanDialog", "--"))
        self.label_40.setText(_translate("QuadScanDialog", "Status"))

from pyqtgraph import ImageView
from striptool import QTangoStripTool
import quadscan_res_rc
