# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quadscan_gui_splitter.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QuadScanDialog(object):
    def setupUi(self, QuadScanDialog):
        QuadScanDialog.setObjectName(_fromUtf8("QuadScanDialog"))
        QuadScanDialog.resize(1088, 923)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/eps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QuadScanDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(QuadScanDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scan_analysis_splitter = QtGui.QSplitter(QuadScanDialog)
        self.scan_analysis_splitter.setStyleSheet(_fromUtf8("QSplitter::handle {\n"
"    image:url(:/icons/vert_splitter_handle.png)\n"
"}"))
        self.scan_analysis_splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.scan_analysis_splitter.setLineWidth(1)
        self.scan_analysis_splitter.setMidLineWidth(0)
        self.scan_analysis_splitter.setOrientation(QtCore.Qt.Vertical)
        self.scan_analysis_splitter.setOpaqueResize(True)
        self.scan_analysis_splitter.setObjectName(_fromUtf8("scan_analysis_splitter"))
        self.upper_area_widget = QtGui.QWidget(self.scan_analysis_splitter)
        self.upper_area_widget.setObjectName(_fromUtf8("upper_area_widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.upper_area_widget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.upper_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.quad_tab = QtGui.QWidget()
        self.quad_tab.setObjectName(_fromUtf8("quad_tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.quad_tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.section_combobox = QtGui.QComboBox(self.quad_tab)
        self.section_combobox.setObjectName(_fromUtf8("section_combobox"))
        self.gridLayout.addWidget(self.section_combobox, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.quad_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.quad_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.quad_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.quad_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.quad_tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.quad_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.quad_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.quad_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.camera_start_button = QtGui.QPushButton(self.quad_tab)
        self.camera_start_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camera_start_button.setObjectName(_fromUtf8("camera_start_button"))
        self.horizontalLayout_3.addWidget(self.camera_start_button)
        self.camera_stop_button = QtGui.QPushButton(self.quad_tab)
        self.camera_stop_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camera_stop_button.setObjectName(_fromUtf8("camera_stop_button"))
        self.horizontalLayout_3.addWidget(self.camera_stop_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.screen_in_button = QtGui.QPushButton(self.quad_tab)
        self.screen_in_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.screen_in_button.setObjectName(_fromUtf8("screen_in_button"))
        self.horizontalLayout_4.addWidget(self.screen_in_button)
        self.screen_out_button = QtGui.QPushButton(self.quad_tab)
        self.screen_out_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.screen_out_button.setObjectName(_fromUtf8("screen_out_button"))
        self.horizontalLayout_4.addWidget(self.screen_out_button)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 9, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 1)
        self.electron_energy_spinbox = QtGui.QDoubleSpinBox(self.quad_tab)
        self.electron_energy_spinbox.setDecimals(1)
        self.electron_energy_spinbox.setMaximum(5000.0)
        self.electron_energy_spinbox.setObjectName(_fromUtf8("electron_energy_spinbox"))
        self.gridLayout.addWidget(self.electron_energy_spinbox, 6, 1, 1, 1)
        self.quad_screen_dist_label = QtGui.QLabel(self.quad_tab)
        self.quad_screen_dist_label.setObjectName(_fromUtf8("quad_screen_dist_label"))
        self.gridLayout.addWidget(self.quad_screen_dist_label, 5, 1, 1, 1)
        self.quad_length_label = QtGui.QLabel(self.quad_tab)
        self.quad_length_label.setObjectName(_fromUtf8("quad_length_label"))
        self.gridLayout.addWidget(self.quad_length_label, 4, 1, 1, 1)
        self.quad_combobox = QtGui.QComboBox(self.quad_tab)
        self.quad_combobox.setObjectName(_fromUtf8("quad_combobox"))
        self.gridLayout.addWidget(self.quad_combobox, 1, 1, 1, 1)
        self.screen_combobox = QtGui.QComboBox(self.quad_tab)
        self.screen_combobox.setObjectName(_fromUtf8("screen_combobox"))
        self.gridLayout.addWidget(self.screen_combobox, 2, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.quad_tab, _fromUtf8(""))
        self.scan_tab = QtGui.QWidget()
        self.scan_tab.setObjectName(_fromUtf8("scan_tab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.scan_tab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_14 = QtGui.QLabel(self.scan_tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.scan_tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.k_current_spinbox = QtGui.QDoubleSpinBox(self.scan_tab)
        self.k_current_spinbox.setDecimals(3)
        self.k_current_spinbox.setMinimum(-1000.0)
        self.k_current_spinbox.setMaximum(1000.0)
        self.k_current_spinbox.setSingleStep(0.1)
        self.k_current_spinbox.setObjectName(_fromUtf8("k_current_spinbox"))
        self.gridLayout_2.addWidget(self.k_current_spinbox, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.scan_tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.scan_tab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.scan_tab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 5, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.scan_tab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 8, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.scan_tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.k_end_spinbox = QtGui.QDoubleSpinBox(self.scan_tab)
        self.k_end_spinbox.setDecimals(3)
        self.k_end_spinbox.setMinimum(-1000.0)
        self.k_end_spinbox.setMaximum(1000.0)
        self.k_end_spinbox.setSingleStep(0.1)
        self.k_end_spinbox.setObjectName(_fromUtf8("k_end_spinbox"))
        self.horizontalLayout_7.addWidget(self.k_end_spinbox)
        self.set_end_k_button = QtGui.QPushButton(self.scan_tab)
        self.set_end_k_button.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.set_end_k_button.setFont(font)
        self.set_end_k_button.setObjectName(_fromUtf8("set_end_k_button"))
        self.horizontalLayout_7.addWidget(self.set_end_k_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.k_start_spinbox = QtGui.QDoubleSpinBox(self.scan_tab)
        self.k_start_spinbox.setDecimals(3)
        self.k_start_spinbox.setMinimum(-1000.0)
        self.k_start_spinbox.setMaximum(1000.0)
        self.k_start_spinbox.setSingleStep(0.1)
        self.k_start_spinbox.setObjectName(_fromUtf8("k_start_spinbox"))
        self.horizontalLayout_8.addWidget(self.k_start_spinbox)
        self.set_start_k_button = QtGui.QPushButton(self.scan_tab)
        self.set_start_k_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.set_start_k_button.setObjectName(_fromUtf8("set_start_k_button"))
        self.horizontalLayout_8.addWidget(self.set_start_k_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.reprate_spinbox = QtGui.QDoubleSpinBox(self.scan_tab)
        self.reprate_spinbox.setMaximum(200.0)
        self.reprate_spinbox.setObjectName(_fromUtf8("reprate_spinbox"))
        self.gridLayout_2.addWidget(self.reprate_spinbox, 6, 1, 1, 1)
        self.save_path_linedit = QtGui.QLineEdit(self.scan_tab)
        self.save_path_linedit.setObjectName(_fromUtf8("save_path_linedit"))
        self.gridLayout_2.addWidget(self.save_path_linedit, 8, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.scan_tab)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 10, 0, 1, 1)
        self.num_k_spinbox = QtGui.QSpinBox(self.scan_tab)
        self.num_k_spinbox.setMinimum(1)
        self.num_k_spinbox.setMaximum(1000)
        self.num_k_spinbox.setObjectName(_fromUtf8("num_k_spinbox"))
        self.gridLayout_2.addWidget(self.num_k_spinbox, 4, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.scan_tab)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 9, 0, 1, 1)
        self.num_images_spinbox = QtGui.QSpinBox(self.scan_tab)
        self.num_images_spinbox.setMinimum(1)
        self.num_images_spinbox.setMaximum(1000)
        self.num_images_spinbox.setObjectName(_fromUtf8("num_images_spinbox"))
        self.gridLayout_2.addWidget(self.num_images_spinbox, 5, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem4, 3, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 7, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.scan_start_button = QtGui.QPushButton(self.scan_tab)
        self.scan_start_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.scan_start_button.setObjectName(_fromUtf8("scan_start_button"))
        self.horizontalLayout_9.addWidget(self.scan_start_button)
        self.scan_stop_button = QtGui.QPushButton(self.scan_tab)
        self.scan_stop_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.scan_stop_button.setObjectName(_fromUtf8("scan_stop_button"))
        self.horizontalLayout_9.addWidget(self.scan_stop_button)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 10, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_22 = QtGui.QLabel(self.scan_tab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_10.addWidget(self.label_22)
        self.save_name_lineedit = QtGui.QLineEdit(self.scan_tab)
        self.save_name_lineedit.setObjectName(_fromUtf8("save_name_lineedit"))
        self.horizontalLayout_10.addWidget(self.save_name_lineedit)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 9, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scan_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 11, 0, 1, 1)
        self.update_analysis_radiobutton = QtGui.QRadioButton(self.scan_tab)
        self.update_analysis_radiobutton.setChecked(True)
        self.update_analysis_radiobutton.setObjectName(_fromUtf8("update_analysis_radiobutton"))
        self.gridLayout_2.addWidget(self.update_analysis_radiobutton, 11, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.scan_tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 6, 0, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line = QtGui.QFrame(self.upper_area_widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.current_quad_sel_label = QtGui.QLabel(self.upper_area_widget)
        self.current_quad_sel_label.setObjectName(_fromUtf8("current_quad_sel_label"))
        self.horizontalLayout_2.addWidget(self.current_quad_sel_label)
        self.line_2 = QtGui.QFrame(self.upper_area_widget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.camera_state_label = QtGui.QLabel(self.upper_area_widget)
        self.camera_state_label.setObjectName(_fromUtf8("camera_state_label"))
        self.horizontalLayout_2.addWidget(self.camera_state_label)
        self.line_3 = QtGui.QFrame(self.upper_area_widget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.screen_state_label = QtGui.QLabel(self.upper_area_widget)
        self.screen_state_label.setObjectName(_fromUtf8("screen_state_label"))
        self.horizontalLayout_2.addWidget(self.screen_state_label)
        self.line_4 = QtGui.QFrame(self.upper_area_widget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_2.addWidget(self.line_4)
        self.reprate_label = QtGui.QLabel(self.upper_area_widget)
        self.reprate_label.setObjectName(_fromUtf8("reprate_label"))
        self.horizontalLayout_2.addWidget(self.reprate_label)
        self.line_6 = QtGui.QFrame(self.upper_area_widget)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_2.addWidget(self.line_6)
        self.current_k_label = QtGui.QLabel(self.upper_area_widget)
        self.current_k_label.setObjectName(_fromUtf8("current_k_label"))
        self.horizontalLayout_2.addWidget(self.current_k_label)
        self.line_5 = QtGui.QFrame(self.upper_area_widget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_2.addWidget(self.line_5)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.scan_status_label = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        self.scan_status_label.setFont(font)
        self.scan_status_label.setObjectName(_fromUtf8("scan_status_label"))
        self.horizontalLayout_2.addWidget(self.scan_status_label)
        self.scan_progress_label = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        self.scan_progress_label.setFont(font)
        self.scan_progress_label.setObjectName(_fromUtf8("scan_progress_label"))
        self.horizontalLayout_2.addWidget(self.scan_progress_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.camera_widget = ImageView(self.upper_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_widget.sizePolicy().hasHeightForWidth())
        self.camera_widget.setSizePolicy(sizePolicy)
        self.camera_widget.setObjectName(_fromUtf8("camera_widget"))
        self.verticalLayout_3.addWidget(self.camera_widget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem8 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.line_7 = QtGui.QFrame(self.upper_area_widget)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, 6, -1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_34 = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.upper_area_widget)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_4.addWidget(self.label_39, 7, 0, 1, 1)
        self.alpha_label = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alpha_label.setFont(font)
        self.alpha_label.setObjectName(_fromUtf8("alpha_label"))
        self.gridLayout_4.addWidget(self.alpha_label, 1, 1, 1, 1)
        self.eps_label = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.eps_label.setFont(font)
        self.eps_label.setObjectName(_fromUtf8("eps_label"))
        self.gridLayout_4.addWidget(self.eps_label, 3, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_4.addWidget(self.label_35, 3, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_4.addWidget(self.label_37, 2, 0, 1, 1)
        self.status_textedit = QtGui.QTextEdit(self.upper_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_textedit.sizePolicy().hasHeightForWidth())
        self.status_textedit.setSizePolicy(sizePolicy)
        self.status_textedit.setMaximumSize(QtCore.QSize(180, 16777215))
        self.status_textedit.setObjectName(_fromUtf8("status_textedit"))
        self.gridLayout_4.addWidget(self.status_textedit, 6, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_4.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.upper_area_widget)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 6, 0, 1, 1)
        self.beta_label = QtGui.QLabel(self.upper_area_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.beta_label.setFont(font)
        self.beta_label.setObjectName(_fromUtf8("beta_label"))
        self.gridLayout_4.addWidget(self.beta_label, 2, 1, 1, 1)
        self.mouse_label = QtGui.QLabel(self.upper_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouse_label.sizePolicy().hasHeightForWidth())
        self.mouse_label.setSizePolicy(sizePolicy)
        self.mouse_label.setMinimumSize(QtCore.QSize(180, 0))
        self.mouse_label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.mouse_label.setObjectName(_fromUtf8("mouse_label"))
        self.gridLayout_4.addWidget(self.mouse_label, 7, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem9, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.lower_area_widget = QtGui.QWidget(self.scan_analysis_splitter)
        self.lower_area_widget.setStyleSheet(_fromUtf8("\n"
"QSplitter::handle:horizontal {\n"
"    width: 2px;\n"
"};\n"
""))
        self.lower_area_widget.setObjectName(_fromUtf8("lower_area_widget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.lower_area_widget)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtGui.QLabel(self.lower_area_widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        spacerItem10 = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.load_disk_button = QtGui.QPushButton(self.lower_area_widget)
        self.load_disk_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.load_disk_button.setObjectName(_fromUtf8("load_disk_button"))
        self.horizontalLayout_14.addWidget(self.load_disk_button)
        self.load_scan_button = QtGui.QPushButton(self.lower_area_widget)
        self.load_scan_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.load_scan_button.setObjectName(_fromUtf8("load_scan_button"))
        self.horizontalLayout_14.addWidget(self.load_scan_button)
        spacerItem11 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.data_source_label = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_source_label.sizePolicy().hasHeightForWidth())
        self.data_source_label.setSizePolicy(sizePolicy)
        self.data_source_label.setObjectName(_fromUtf8("data_source_label"))
        self.horizontalLayout_14.addWidget(self.data_source_label)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.p_quad_length_label = QtGui.QLabel(self.lower_area_widget)
        self.p_quad_length_label.setObjectName(_fromUtf8("p_quad_length_label"))
        self.gridLayout_3.addWidget(self.p_quad_length_label, 2, 1, 1, 1)
        self.p_quad_screen_dist_label = QtGui.QLabel(self.lower_area_widget)
        self.p_quad_screen_dist_label.setObjectName(_fromUtf8("p_quad_screen_dist_label"))
        self.gridLayout_3.addWidget(self.p_quad_screen_dist_label, 3, 1, 1, 1)
        self.p_electron_energy_label = QtGui.QLabel(self.lower_area_widget)
        self.p_electron_energy_label.setObjectName(_fromUtf8("p_electron_energy_label"))
        self.gridLayout_3.addWidget(self.p_electron_energy_label, 4, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 13, 0, 1, 1)
        self.process_button = QtGui.QPushButton(self.lower_area_widget)
        self.process_button.setObjectName(_fromUtf8("process_button"))
        self.gridLayout_3.addWidget(self.process_button, 16, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 4, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 11, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 12, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 3, 0, 1, 1)
        self.p_median_kernel_spinbox = QtGui.QSpinBox(self.lower_area_widget)
        self.p_median_kernel_spinbox.setMinimum(1)
        self.p_median_kernel_spinbox.setMaximum(21)
        self.p_median_kernel_spinbox.setSingleStep(2)
        self.p_median_kernel_spinbox.setProperty("value", 3)
        self.p_median_kernel_spinbox.setObjectName(_fromUtf8("p_median_kernel_spinbox"))
        self.gridLayout_3.addWidget(self.p_median_kernel_spinbox, 14, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 14, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_3.addWidget(self.label_30, 15, 0, 1, 1)
        self.p_threshold_spinbox = QtGui.QDoubleSpinBox(self.lower_area_widget)
        self.p_threshold_spinbox.setMaximum(66000.0)
        self.p_threshold_spinbox.setObjectName(_fromUtf8("p_threshold_spinbox"))
        self.gridLayout_3.addWidget(self.p_threshold_spinbox, 13, 1, 1, 1)
        self.fit_algo_combobox = QtGui.QComboBox(self.lower_area_widget)
        self.fit_algo_combobox.setObjectName(_fromUtf8("fit_algo_combobox"))
        self.gridLayout_3.addWidget(self.fit_algo_combobox, 15, 1, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.p_roi_cent_x_spinbox = QtGui.QDoubleSpinBox(self.lower_area_widget)
        self.p_roi_cent_x_spinbox.setMaximum(5000.0)
        self.p_roi_cent_x_spinbox.setObjectName(_fromUtf8("p_roi_cent_x_spinbox"))
        self.horizontalLayout_12.addWidget(self.p_roi_cent_x_spinbox)
        self.p_roi_cent_y_spinbox = QtGui.QDoubleSpinBox(self.lower_area_widget)
        self.p_roi_cent_y_spinbox.setMaximum(5000.0)
        self.p_roi_cent_y_spinbox.setObjectName(_fromUtf8("p_roi_cent_y_spinbox"))
        self.horizontalLayout_12.addWidget(self.p_roi_cent_y_spinbox)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 11, 1, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.p_roi_size_w_spinbox = QtGui.QDoubleSpinBox(self.lower_area_widget)
        self.p_roi_size_w_spinbox.setMaximum(5000.0)
        self.p_roi_size_w_spinbox.setObjectName(_fromUtf8("p_roi_size_w_spinbox"))
        self.horizontalLayout_13.addWidget(self.p_roi_size_w_spinbox)
        self.p_roi_size_h_spinbox = QtGui.QDoubleSpinBox(self.lower_area_widget)
        self.p_roi_size_h_spinbox.setMaximum(5000.0)
        self.p_roi_size_h_spinbox.setObjectName(_fromUtf8("p_roi_size_h_spinbox"))
        self.horizontalLayout_13.addWidget(self.p_roi_size_h_spinbox)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 12, 1, 1, 1)
        self.p_image_index_slider = QtGui.QSlider(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_image_index_slider.sizePolicy().hasHeightForWidth())
        self.p_image_index_slider.setSizePolicy(sizePolicy)
        self.p_image_index_slider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.p_image_index_slider.setMaximum(10)
        self.p_image_index_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_image_index_slider.setInvertedControls(False)
        self.p_image_index_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.p_image_index_slider.setObjectName(_fromUtf8("p_image_index_slider"))
        self.gridLayout_3.addWidget(self.p_image_index_slider, 7, 1, 1, 1)
        self.p_k_index_slider = QtGui.QSlider(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_k_index_slider.sizePolicy().hasHeightForWidth())
        self.p_k_index_slider.setSizePolicy(sizePolicy)
        self.p_k_index_slider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.p_k_index_slider.setMaximum(10)
        self.p_k_index_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_k_index_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.p_k_index_slider.setObjectName(_fromUtf8("p_k_index_slider"))
        self.gridLayout_3.addWidget(self.p_k_index_slider, 6, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem12, 5, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem13, 9, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 6, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 7, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.lower_area_widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 8, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.p_raw_image_radio = QtGui.QRadioButton(self.lower_area_widget)
        self.p_raw_image_radio.setObjectName(_fromUtf8("p_raw_image_radio"))
        self.buttonGroup = QtGui.QButtonGroup(QuadScanDialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.p_raw_image_radio)
        self.horizontalLayout_15.addWidget(self.p_raw_image_radio)
        self.p_filtered_image_radio = QtGui.QRadioButton(self.lower_area_widget)
        self.p_filtered_image_radio.setChecked(True)
        self.p_filtered_image_radio.setObjectName(_fromUtf8("p_filtered_image_radio"))
        self.buttonGroup.addButton(self.p_filtered_image_radio)
        self.horizontalLayout_15.addWidget(self.p_filtered_image_radio)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 8, 1, 1, 1)
        self.horizontalLayout_16.addLayout(self.gridLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_3 = QtGui.QWidget(self.lower_area_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setContentsMargins(-1, 3, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.analysis_pic_plot_splitter = QtGui.QSplitter(self.widget_3)
        self.analysis_pic_plot_splitter.setStyleSheet(_fromUtf8("QSplitter::handle {\n"
"    image:url(:/icons/hor_splitter_handle.png);\n"
"    width: 15px;\n"
"    height: 10px;\n"
"}"))
        self.analysis_pic_plot_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.analysis_pic_plot_splitter.setObjectName(_fromUtf8("analysis_pic_plot_splitter"))
        self.widget_7 = QtGui.QWidget(self.analysis_pic_plot_splitter)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.line_10 = QtGui.QFrame(self.widget_7)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_11.addWidget(self.line_10)
        self.p_k_value_label = QtGui.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.p_k_value_label.setFont(font)
        self.p_k_value_label.setObjectName(_fromUtf8("p_k_value_label"))
        self.horizontalLayout_11.addWidget(self.p_k_value_label)
        self.line_8 = QtGui.QFrame(self.widget_7)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_11.addWidget(self.line_8)
        self.p_k_ind_label = QtGui.QLabel(self.widget_7)
        self.p_k_ind_label.setObjectName(_fromUtf8("p_k_ind_label"))
        self.horizontalLayout_11.addWidget(self.p_k_ind_label)
        self.line_9 = QtGui.QFrame(self.widget_7)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_11.addWidget(self.line_9)
        self.p_image_label = QtGui.QLabel(self.widget_7)
        self.p_image_label.setObjectName(_fromUtf8("p_image_label"))
        self.horizontalLayout_11.addWidget(self.p_image_label)
        self.line_11 = QtGui.QFrame(self.widget_7)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout_11.addWidget(self.line_11)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.process_image_widget = ImageView(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_image_widget.sizePolicy().hasHeightForWidth())
        self.process_image_widget.setSizePolicy(sizePolicy)
        self.process_image_widget.setObjectName(_fromUtf8("process_image_widget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.process_image_widget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6.addWidget(self.process_image_widget)
        self.widget_4 = QtGui.QWidget(self.analysis_pic_plot_splitter)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(-1, 3, -1, 0)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_12 = QtGui.QLabel(self.widget_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_5.addWidget(self.label_12)
        self.analysis_plots_splitter = QtGui.QSplitter(self.widget_4)
        self.analysis_plots_splitter.setStyleSheet(_fromUtf8("QSplitter::handle {\n"
"    image:url(:/icons/vert_splitter_handle.png)\n"
"}"))
        self.analysis_plots_splitter.setOrientation(QtCore.Qt.Vertical)
        self.analysis_plots_splitter.setObjectName(_fromUtf8("analysis_plots_splitter"))
        self.fit_widget = PlotWidget(self.analysis_plots_splitter)
        self.fit_widget.setObjectName(_fromUtf8("fit_widget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.fit_widget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.charge_widget = PlotWidget(self.analysis_plots_splitter)
        self.charge_widget.setObjectName(_fromUtf8("charge_widget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.charge_widget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_5.addWidget(self.analysis_plots_splitter)
        self.verticalLayout_4.addWidget(self.analysis_pic_plot_splitter)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_16.addLayout(self.verticalLayout_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.verticalLayout.addWidget(self.scan_analysis_splitter)

        self.retranslateUi(QuadScanDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(QuadScanDialog)

    def retranslateUi(self, QuadScanDialog):
        QuadScanDialog.setWindowTitle(_translate("QuadScanDialog", "Dialog", None))
        self.label.setText(_translate("QuadScanDialog", "Section", None))
        self.label_2.setText(_translate("QuadScanDialog", "Quad", None))
        self.label_3.setText(_translate("QuadScanDialog", "Screen", None))
        self.label_6.setText(_translate("QuadScanDialog", "Electron energy", None))
        self.label_7.setText(_translate("QuadScanDialog", "Camera", None))
        self.label_5.setText(_translate("QuadScanDialog", "Quad-screen dist", None))
        self.label_4.setText(_translate("QuadScanDialog", "Quad length", None))
        self.label_8.setText(_translate("QuadScanDialog", "Screen", None))
        self.camera_start_button.setText(_translate("QuadScanDialog", "Start", None))
        self.camera_stop_button.setText(_translate("QuadScanDialog", "Stop", None))
        self.screen_in_button.setText(_translate("QuadScanDialog", "In", None))
        self.screen_out_button.setText(_translate("QuadScanDialog", "Out", None))
        self.electron_energy_spinbox.setSuffix(_translate("QuadScanDialog", " MeV", None))
        self.quad_screen_dist_label.setText(_translate("QuadScanDialog", "TextLabel", None))
        self.quad_length_label.setText(_translate("QuadScanDialog", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.quad_tab), _translate("QuadScanDialog", "Quad", None))
        self.label_14.setText(_translate("QuadScanDialog", "k start", None))
        self.label_15.setText(_translate("QuadScanDialog", "k end", None))
        self.k_current_spinbox.setSuffix(_translate("QuadScanDialog", " 1/m²", None))
        self.label_16.setText(_translate("QuadScanDialog", "Num k", None))
        self.label_18.setText(_translate("QuadScanDialog", "Rep rate", None))
        self.label_17.setText(_translate("QuadScanDialog", "Num images", None))
        self.label_19.setText(_translate("QuadScanDialog", "Save dir", None))
        self.label_13.setText(_translate("QuadScanDialog", "k current", None))
        self.k_end_spinbox.setSuffix(_translate("QuadScanDialog", " 1/m²", None))
        self.set_end_k_button.setText(_translate("QuadScanDialog", "<╝", None))
        self.k_start_spinbox.setSuffix(_translate("QuadScanDialog", " 1/m²", None))
        self.set_start_k_button.setText(_translate("QuadScanDialog", "<╝", None))
        self.label_21.setText(_translate("QuadScanDialog", "Scan", None))
        self.label_20.setText(_translate("QuadScanDialog", "Save name", None))
        self.scan_start_button.setText(_translate("QuadScanDialog", "START", None))
        self.scan_stop_button.setText(_translate("QuadScanDialog", "STOP", None))
        self.label_22.setText(_translate("QuadScanDialog", "TextLabel", None))
        self.label_9.setText(_translate("QuadScanDialog", "Analysis", None))
        self.update_analysis_radiobutton.setText(_translate("QuadScanDialog", "Update while scan", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scan_tab), _translate("QuadScanDialog", "Scan", None))
        self.current_quad_sel_label.setText(_translate("QuadScanDialog", "---", None))
        self.camera_state_label.setText(_translate("QuadScanDialog", "RUNNING", None))
        self.screen_state_label.setText(_translate("QuadScanDialog", "IN", None))
        self.reprate_label.setText(_translate("QuadScanDialog", "-- Hz", None))
        self.current_k_label.setText(_translate("QuadScanDialog", "k=-.-- 1/m²", None))
        self.scan_status_label.setText(_translate("QuadScanDialog", "PAUSED: k -/- image -/- ", None))
        self.scan_progress_label.setText(_translate("QuadScanDialog", "[≡≡≡≡≡≡-------]", None))
        self.label_34.setText(_translate("QuadScanDialog", "Result", None))
        self.label_39.setText(_translate("QuadScanDialog", "Mouse", None))
        self.alpha_label.setText(_translate("QuadScanDialog", "--.-", None))
        self.eps_label.setText(_translate("QuadScanDialog", "--.- mm x mmrad", None))
        self.label_35.setText(_translate("QuadScanDialog", "ε<sub>N</sub>", None))
        self.label_37.setText(_translate("QuadScanDialog", "β", None))
        self.label_38.setText(_translate("QuadScanDialog", "α", None))
        self.label_40.setText(_translate("QuadScanDialog", "Status", None))
        self.beta_label.setText(_translate("QuadScanDialog", "--.- m", None))
        self.mouse_label.setText(_translate("QuadScanDialog", "--", None))
        self.label_10.setText(_translate("QuadScanDialog", "Load data from", None))
        self.load_disk_button.setText(_translate("QuadScanDialog", "DISK", None))
        self.load_scan_button.setText(_translate("QuadScanDialog", "Scan", None))
        self.data_source_label.setText(_translate("QuadScanDialog", "--- No data loaded ---", None))
        self.p_quad_length_label.setText(_translate("QuadScanDialog", "-.-- m", None))
        self.p_quad_screen_dist_label.setText(_translate("QuadScanDialog", "-.-- m", None))
        self.p_electron_energy_label.setText(_translate("QuadScanDialog", "--- MeV", None))
        self.label_28.setText(_translate("QuadScanDialog", "Threshold", None))
        self.process_button.setText(_translate("QuadScanDialog", "Process", None))
        self.label_25.setText(_translate("QuadScanDialog", "Electron energy", None))
        self.label_26.setText(_translate("QuadScanDialog", "ROI cent (x, y)", None))
        self.label_27.setText(_translate("QuadScanDialog", "ROI size (w / h)", None))
        self.label_23.setText(_translate("QuadScanDialog", "Quad length", None))
        self.label_24.setText(_translate("QuadScanDialog", "Quad screen dist", None))
        self.label_29.setText(_translate("QuadScanDialog", "Median kernel", None))
        self.label_30.setText(_translate("QuadScanDialog", "Fit algorithm", None))
        self.label_31.setText(_translate("QuadScanDialog", "Select k", None))
        self.label_32.setText(_translate("QuadScanDialog", "Select image", None))
        self.label_11.setText(_translate("QuadScanDialog", "Show", None))
        self.p_raw_image_radio.setText(_translate("QuadScanDialog", "Raw", None))
        self.p_filtered_image_radio.setText(_translate("QuadScanDialog", "Filtered", None))
        self.p_k_value_label.setText(_translate("QuadScanDialog", "k = -.-- 1/m²", None))
        self.p_k_ind_label.setText(_translate("QuadScanDialog", "k index 0/0", None))
        self.p_image_label.setText(_translate("QuadScanDialog", "image 0/0", None))
        self.label_12.setText(_translate("QuadScanDialog", "Fit", None))

from pyqtgraph import ImageView, PlotWidget
import quadscan_res_rc
